### ISSUE TITLE
Plover won't start on Ubuntu 18.10 (KDE) and 18.04 (Unity). launch.sh works.

### ISSUE THREAD

**Issue by Elktro** [openstenoproject/plover#1083]
## Summary

Plover won't start after installation and gives an error on Ubuntu 18.10 (KDE) and 18.04 (Unity). Using launch.sh works just fine.

## Reproducing
1. Git clone Plover repository.
2. $./setup.py install --user
3. Try to run plover with "plover" command 

```
$ plover
Traceback (most recent call last):
  File "/home/username/.local/bin/plover", line 11, in <module>
    load_entry_point('plover==4.0.0.dev8', 'console_scripts', 'plover')()
  File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/username/.local/lib/python3.6/site-packages/plover-4.0.0.dev8-py3.6.egg/plover/main.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/username/.local/lib/python3.6/site-packages/plover-4.0.0.dev8-py3.6.egg/plover/config.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/username/.local/lib/python3.6/site-packages/plover-4.0.0.dev8-py3.6.egg/plover/machine/keymap.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/username/.local/lib/python3.6/site-packages/plover-4.0.0.dev8-py3.6.egg/plover/log.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/username/.local/lib/python3.6/site-packages/plover-4.0.0.dev8-py3.6.egg/plover/oslayer/config.py", line 41, in <module>
  File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1647, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1663, in _extract_resource
    manager, os.path.join(zip_path, name)
  File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1675, in _extract_resource
    real_path = manager.get_cache_path(
AttributeError: 'str' object has no attribute 'get_cache_path'
```

Plover can be started just fine using launch.sh

## Plover Version

Tested with f4e45364fc5f58745c459f878d13ec6442497f46

## System

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic
```
KDE, Unity

**Comment by benoit-pierre** [comment]
Hard to know what went wrong, but using `./setup.py install` over `pip install .` is a bad idea (since it will use `easy_install`, which is deprecated). I'm going to close. Feel free to re-open if you can reproduce with a more recent version, and when installing with pip.
