### ISSUE TITLE
Plugin manager doesn't show under tool menu in archlinux

### ISSUE THREAD

**Issue by erlanger** [openstenoproject/plover#1090]
## Summary

The Plugin manager doesn't show under tool menu in archlinux

## Reproducing

Just open the tools menu and you'll see the plugin manager doesn't show up.

## Plover Version

4.0.0.dev8+161.gf4e4536 

## System

Archilunx

**Comment by antistic** [comment]
The problem is that the plugins manager isn't installed (not entirely sure why?). You need to run `pip install plover-plugins-manager`, restart plover, and it should work.

I've added this info to the wiki, but maybe we should have the plugins manager installed with plover by default?

**Comment by MarkoSchuetz** [comment]
I did what is suggested here, but I still do not have the plugins manager available. I_think_ it was available not so long ago. This is what I get with 4.0.0.dev10+146.g3e7ba1a: 

````
2022-02-10 12:54:45,705 [MainThread] ERROR: error loading gui.qt.tool plugin: plugins_manager (from plover_plugins_manager.gui_qt.manager)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/plover/registry.py", line 56, in register_plugin_from_entrypoint
    obj = entrypoint.load()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2464, in load
    return self.resolve()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2470, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.10/site-packages/plover_plugins_manager/gui_qt/manager.py", line 13, in <module>
    from plover_plugins_manager.gui_qt.info_browser import InfoBrowser
  File "/usr/lib/python3.10/site-packages/plover_plugins_manager/gui_qt/info_browser.py", line 5, in <module>
    from plover_plugins_manager.requests import CachedSession, FuturesSession
  File "/usr/lib/python3.10/site-packages/plover_plugins_manager/requests.py", line 4, in <module>
    from requests_cache import CachedSession
  File "/usr/lib/python3.10/site-packages/requests_cache/__init__.py", line 11, in <module>
    from .backends import *
  File "/usr/lib/python3.10/site-packages/requests_cache/backends/__init__.py", line 7, in <module>
    from .base import BaseCache, BaseStorage, DictStorage
  File "/usr/lib/python3.10/site-packages/requests_cache/backends/base.py", line 18, in <module>
    from ..serializers import init_serializer
  File "/usr/lib/python3.10/site-packages/requests_cache/serializers/__init__.py", line 6, in <module>
    from .preconf import (
  File "/usr/lib/python3.10/site-packages/requests_cache/serializers/preconf.py", line 27, in <module>
    CattrStage()
  File "/usr/lib/python3.10/site-packages/requests_cache/serializers/cattrs.py", line 32, in __init__
    self.converter = init_converter(factory)
  File "/usr/lib/python3.10/site-packages/requests_cache/serializers/cattrs.py", line 69, in init_converter
    converter.register_structure_hook(
  File "/usr/lib/python3.10/site-packages/cattr/converters.py", line 269, in register_structure_hook
    self._structure_func.register_cls_list([(cl, func)])
  File "/usr/lib/python3.10/site-packages/cattr/dispatch.py", line 57, in register_cls_list
    self._single_dispatch.register(cls, handler)
  File "/usr/lib/python3.10/functools.py", line 856, in register
    raise TypeError(
TypeError: Invalid first argument to `register()`. ForwardRef('CachedResponse') is not a class.
QSettings::value: Empty key passed
QSettings::value: Empty key passed
````

**Comment by antistic** [comment]
My answer above is out of date — on archlinux there is now an AUR package `plover_plugins_manager` https://aur.archlinux.org/packages/plover_plugins_manager.

**Comment by MarkoSchuetz** [comment]
@benoit-pierre : I can confirm that updating `requests-cache` resolves the issue for me.

**Comment by MarkoSchuetz** [comment]
OK it did for a little and now I seem to be running into the issue with `cmarkgfm` and `readme-renderer`. Any suggestions?

**Comment by mkrnr** [comment]
Closing this since the plugins manger is now integrated into Plover.
