### ISSUE TITLE
'Engine' object has no attribute 'config'

### ISSUE THREAD

**Issue by mulka** [openstenoproject/plover#1100]
## Summary

I just cloned the master branch, installed Python 3.6 and pip installed from requirements.txt, but am getting this error when running "./launch.sh":

Traceback (most recent call last):
  File "/Users/mulka/Documents/Code/personal/plover/plover/main.py", line 128, in main
    code = gui.main(config)
  File "/Users/mulka/Documents/Code/personal/plover/plover/gui_qt/main.py", line 87, in main
    app = Application(config, use_qt_notifications)
  File "/Users/mulka/Documents/Code/personal/plover/plover/gui_qt/main.py", line 63, in __init__
    self._win = MainWindow(self._engine, use_qt_notifications)
  File "/Users/mulka/Documents/Code/personal/plover/plover/gui_qt/main_window.py", line 139, in __init__
    config = self._engine.config
AttributeError: 'Engine' object has no attribute 'config'

## Reproducing

clone master branch
install Python 3.6
pip install from requirements.txt
run ./launch.sh

## Plover Version

master branch
SHA: f4e4536

## System

Mac
10.15.3 (19D76)

**Comment by greenwyrt** [comment]
Closing due to age of issue and python 3.6 no longer being supported in current version.
