### ISSUE TITLE
Errors running from source

### ISSUE THREAD

**Issue by excalamus** [openstenoproject/plover#1124]
## Summary
Calling `python plover\main.py` causes many pop-ups indicating ERROR to appear, along with the following barf:

```
(venv) C:\projects\plover>python plover\main.py
2020-05-08 14:27:26,813 [MainThread] ERROR: error loading gui.qt.machine_option plugin: plover.machine.base:SerialStenotypeBase (from plover.gui_qt.machine_options)
Traceback (most recent call last):
  File "c:\projects\plover\plover\registry.py", line 56, in register_plugin_from_entrypoint
    obj = entrypoint.load()
  File "C:\projects\plover\venv\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "C:\projects\plover\venv\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\projects\plover\plover\gui_qt\machine_options.py", line 9, in <module>
    from plover.gui_qt.config_keyboard_widget_ui import Ui_KeyboardWidget
ModuleNotFoundError: No module named 'plover.gui_qt.config_keyboard_widget_ui'
2020-05-08 14:27:26,824 [MainThread] ERROR: error loading gui.qt.machine_option plugin: plover.machine.keyboard:Keyboard (from plover.gui_qt.machine_options)
Traceback (most recent call last):
  File "c:\projects\plover\plover\registry.py", line 56, in register_plugin_from_entrypoint
    obj = entrypoint.load()
  File "C:\projects\plover\venv\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "C:\projects\plover\venv\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\projects\plover\plover\gui_qt\machine_options.py", line 9, in <module>
    from plover.gui_qt.config_keyboard_widget_ui import Ui_KeyboardWidget
ModuleNotFoundError: No module named 'plover.gui_qt.config_keyboard_widget_ui'
2020-05-08 14:27:27,218 [MainThread] ERROR: error loading gui.qt.tool plugin: add_translation (from plover.gui_qt.add_translation_dialog)
Traceback (most recent call last):
  File "c:\projects\plover\plover\registry.py", line 56, in register_plugin_from_entrypoint
    obj = entrypoint.load()
  File "C:\projects\plover\venv\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "C:\projects\plover\venv\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\projects\plover\plover\gui_qt\add_translation_dialog.py", line 1, in <module>
    from plover.gui_qt.add_translation_dialog_ui import Ui_AddTranslationDialog
ModuleNotFoundError: No module named 'plover.gui_qt.add_translation_dialog_ui'
2020-05-08 14:27:27,222 [MainThread] ERROR: error loading gui.qt.tool plugin: lookup (from plover.gui_qt.lookup_dialog)
Traceback (most recent call last):
  File "c:\projects\plover\plover\registry.py", line 56, in register_plugin_from_entrypoint
    obj = entrypoint.load()
  File "C:\projects\plover\venv\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "C:\projects\plover\venv\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\projects\plover\plover\gui_qt\lookup_dialog.py", line 6, in <module>
    from plover.gui_qt.lookup_dialog_ui import Ui_LookupDialog
ModuleNotFoundError: No module named 'plover.gui_qt.lookup_dialog_ui'
2020-05-08 14:27:27,231 [MainThread] ERROR: error loading gui.qt.tool plugin: paper_tape (from plover.gui_qt.paper_tape)
Traceback (most recent call last):
  File "c:\projects\plover\plover\registry.py", line 56, in register_plugin_from_entrypoint
    obj = entrypoint.load()
  File "C:\projects\plover\venv\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "C:\projects\plover\venv\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\projects\plover\plover\gui_qt\paper_tape.py", line 16, in <module>
    from plover.gui_qt.paper_tape_ui import Ui_PaperTape
ModuleNotFoundError: No module named 'plover.gui_qt.paper_tape_ui'
2020-05-08 14:27:27,234 [MainThread] ERROR: error loading gui.qt.tool plugin: suggestions (from plover.gui_qt.suggestions_dialog)
Traceback (most recent call last):
  File "c:\projects\plover\plover\registry.py", line 56, in register_plugin_from_entrypoint
    obj = entrypoint.load()
  File "C:\projects\plover\venv\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "C:\projects\plover\venv\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\projects\plover\plover\gui_qt\suggestions_dialog.py", line 18, in <module>
    from plover.gui_qt.suggestions_dialog_ui import Ui_SuggestionsDialog
ModuleNotFoundError: No module named 'plover.gui_qt.suggestions_dialog_ui'
Unexpected error: Traceback (most recent call last):
  File "plover\main.py", line 127, in main
    code = gui.main(config)
  File "c:\projects\plover\plover\gui_qt\main.py", line 87, in main
    app = Application(config, use_qt_notifications)
  File "c:\projects\plover\plover\gui_qt\main.py", line 27, in __init__
    from plover.gui_qt.main_window import MainWindow
  File "c:\projects\plover\plover\gui_qt\main_window.py", line 22, in <module>
    from plover.gui_qt.main_window_ui import Ui_MainWindow
ModuleNotFoundError: No module named 'plover.gui_qt.main_window_ui'

Exception ignored in: <bound method Application.__del__ of <plover.gui_qt.main.Application object at 0x0477DA10>>
Traceback (most recent call last):
  File "c:\projects\plover\plover\gui_qt\main.py", line 66, in __del__
    del self._win
AttributeError: _win
```

## Reproducing
As you can see, I have created a virtual environment.  It is my practice to install Python to C:\python and not add it to PATH, as I have had too many conflicts using multiple versions on the same machine.  Hence my deviation from [https://github.com/openstenoproject/plover/blob/master/windows/README.md](https://github.com/openstenoproject/plover/blob/master/windows/README.md)  

The steps I have taken are:

```
C:\projects\plover>c:\python\python3.6.8-32\python.exe -m venv venv
C:\projects\plover>venv\Scripts\activate
(venv) C:\projects\plover>python -m pip install -r requirements.txt
(venv) C:\projects\plover>pip install -e .
(venv) C:\projects\plover>pip install -e . -r requirements_plugins.txt
(venv) C:\projects\plover>python plover\main.py
```

## Plover Version
1788f74

## System
Windows 10

**Comment by benoit-pierre** [comment]
You need to generate the UI files: `python setup.py build_ui`.

**Comment by excalamus** [comment]
That solves it.  Thank you.  

I have written up detailed Windows install instructions and would like to submit a pull request.  I will need help with this.  I am unfamiliar with some of the requirements given in the developer_guide.rst.

**Comment by gdwaynewarner** [comment]
Is there something similar for the Mac OS? Upgraded the laptop to el Crapitan recently.
