### ISSUE TITLE
plover crashes in linux (void): Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Invalid MIT-MAGIC-COOKIE-1 key'

### ISSUE THREAD

**Issue by zenny** [openstenoproject/plover#1137]
Hi,

Just installed plover 4-dev using `pip` (The error popped up with v 3.1.1 so installed anew), but it crashes with the following error:

```
$ plover --version
Plover 4.0.0.dev8
```

The crash error while launching `plover` was:

```
$ plover
Unexpected error: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/plover/main.py", line 128, in main
    code = gui.main(config)
  File "/usr/lib/python3.8/site-packages/plover/gui_qt/main.py", line 88, in main
    app = Application(config, use_qt_notifications)
  File "/usr/lib/python3.8/site-packages/plover/gui_qt/main.py", line 28, in __init__
    from plover.gui_qt.main_window import MainWindow
  File "/usr/lib/python3.8/site-packages/plover/gui_qt/main_window.py", line 13, in <module>
    from plover.oslayer import wmctrl
  File "/usr/lib/python3.8/site-packages/plover/oslayer/wmctrl.py", line 34, in <module>
    wmctrl = WmCtrl()
  File "/usr/lib/python3.8/site-packages/plover/oslayer/xwmctrl.py", line 9, in __init__
    self._display = display.Display()
  File "/home/zenny/.local/lib/python3.8/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/home/zenny/.local/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/home/zenny/.local/lib/python3.8/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Invalid MIT-MAGIC-COOKIE-1 key'

Exception ignored in: <function Application.__del__ at 0x7f01015c1dc0>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/plover/gui_qt/main.py", line 67, in __del__
    del self._win
AttributeError: _win
```

Qt-gui interface looks like:

![pic-selected-200726-0637-51](https://user-images.githubusercontent.com/1653166/88471525-c0d49000-cf0a-11ea-97dc-8029a703efa3.png)

Cheers, and remain safe
/z

**Comment by gdwaynewarner** [comment]
I've only used Plover for about a minute on Linux, but on my Mac, when I upgraded from 3.x to 4.x, I had problems because the system was looking at the preferences for version 3.x.

I had to delete the old preferences and have the new version create its own preferences file before the new version would work.

**Comment by zenny** [comment]
> I've only used Plover for about a minute on Linux, but on my Mac, when I upgraded from 3.x to 4.x, I had problems because the system was looking at the preferences for version 3.x.
> 
> I had to delete the old preferences and have the new version create its own preferences file before the new version would work.

In my case, there is no leftover configs from version 3.0 as evident from:

```
$ ls -la ~/.config/plover
ls: cannot access '/home/zenny/.config/plover': No such file or directory
```
The only file that is left was an empty lock file in the `~/` directory which I deleted manually yet the error persists:

```
$ file ~/.plover-lock-MACHINE-GA-970A-D3-0
.plover-lock-MACHINE-GA-970A-D3-0: empty

$ rm ~/.plover-lock-MACHINE-GA-970A-D3-0
removed '/home/zenny/.plover-lock-MACHINE-GA-970A-D3-0'

$ plover
Unexpected error: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/plover/main.py", line 128, in main
    code = gui.main(config)
  File "/usr/lib/python3.8/site-packages/plover/gui_qt/main.py", line 88, in main
    app = Application(config, use_qt_notifications)
  File "/usr/lib/python3.8/site-packages/plover/gui_qt/main.py", line 28, in __init__
    from plover.gui_qt.main_window import MainWindow
  File "/usr/lib/python3.8/site-packages/plover/gui_qt/main_window.py", line 13, in <module>
    from plover.oslayer import wmctrl
  File "/usr/lib/python3.8/site-packages/plover/oslayer/wmctrl.py", line 34, in <module>
    wmctrl = WmCtrl()
  File "/usr/lib/python3.8/site-packages/plover/oslayer/xwmctrl.py", line 9, in __init__
    self._display = display.Display()
  File "/home/zenny/.local/lib/python3.8/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/home/zenny/.local/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/home/zenny/.local/lib/python3.8/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Invalid MIT-MAGIC-COOKIE-1 key'

Exception ignored in: <function Application.__del__ at 0x7f4866312dc0>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/plover/gui_qt/main.py", line 67, in __del__
    del self._win
AttributeError: _win
```

**Comment by gdwaynewarner** [comment]
Unfortunately, my Linux experience was a long time ago, so I will have to leave that one to someone with a lot more Linux experience than mine.

Sorry ... and good luck!

**Comment by Trevortds** [comment]
Adding to this thread: I am encountering this error as well, but only on the user account that I did not use to install plover. 

Deleting ~/.Xauthority and then relogging solved the issue for me. 

Got the idea from this thread: https://github.com/autokey/autokey/issues/166

(Manjaro i3, plover-git 4.0.0.dev8.223.g26aacfa-1 from AUR)

**Comment by benoit-pierre** [comment]
Clearly a connection issue, which version of `python-xlib`? Is it reproducible with `python -c 'from Xlib.display import Display; Display()'`?
