### ISSUE TITLE
`setup.py launch` doesn't regenerate UI files on git version update?

### ISSUE THREAD

**Issue by user202729** [openstenoproject/plover#1269]
**Note** I guess setup.py launch is not supported anymore (use tox instead)? Then perhaps that command should be removed?

**Describe the bug**

If I upgrade Plover with `git pull upstream/master` or similar, then reinstall the package, the `_ui.py` files might not be correctly regenerated.

**To Reproduce**

```
$ git checkout edcb7d20e0b5ae44f7ad017bbac1ce9cc479c1e4
Previous HEAD position was [...]
HEAD is now at edcb7d2 setup: use README.md for the long description contents

$ python setup.py launch
running launch
running build_py
running build_ui
[...]
copying plover_build_utils/functions.sh -> build/lib/plover_build_utils
running build_ext
[Plover runs normally]

$ git checkout upstream/master
Previous HEAD position was edcb7d2 setup: use README.md for the long description contents
HEAD is now at 971d3f5 Merge pull request #1263 from nvdaes/esUpdate

$ python setup.py launch
running launch
running build_py
running build_ui
running egg_info
writing plover.egg-info/PKG-INFO
writing dependency_links to plover.egg-info/dependency_links.txt
writing entry points to plover.egg-info/entry_points.txt
writing requirements to plover.egg-info/requires.txt
writing top-level names to plover.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
warning: no files found matching 'launch.bat'
warning: no files found matching 'launch.sh'
warning: no files found matching 'test.bat'
warning: no files found matching 'test.sh'
warning: no previously-included files found matching 'archlinux/.gitignore'
writing manifest file 'plover.egg-info/SOURCES.txt'
generating ui (hooks: fix_icons, no_autoconnection, gettext)
generating plover/gui_qt/add_translation_dialog_ui.py
generating plover/gui_qt/config_file_widget_ui.py
generating plover/gui_qt/config_keyboard_widget_ui.py
generating plover/gui_qt/config_serial_widget_ui.py
generating plover/gui_qt/dictionaries_widget_ui.py
generating plover/gui_qt/paper_tape_ui.py
generating plover/gui_qt/suggestions_dialog_ui.py
generating plover/gui_qt/suggestions_widget_ui.py
generating plover/gui_qt/resources_rc.py
running compile_catalog
compiling catalog plover/messages/fr/LC_MESSAGES/plover.po to plover/messages/fr/LC_MESSAGES/plover.mo
compiling catalog plover/messages/nl/LC_MESSAGES/plover.po to plover/messages/nl/LC_MESSAGES/plover.mo
compiling catalog plover/messages/es/LC_MESSAGES/plover.po to plover/messages/es/LC_MESSAGES/plover.mo
copying plover/i18n.py -> build/lib/plover
copying plover/dist_main.py -> build/lib/plover
copying plover/__init__.py -> build/lib/plover
copying plover/gui_qt/dictionaries_widget.py -> build/lib/plover/gui_qt
copying plover/gui_qt/main_window.py -> build/lib/plover/gui_qt
copying plover/gui_qt/dictionaries_widget_ui.py -> build/lib/plover/gui_qt
copying plover/gui_qt/suggestions_widget_ui.py -> build/lib/plover/gui_qt
copying plover/gui_qt/paper_tape.py -> build/lib/plover/gui_qt
copying plover/gui_qt/machine_options.py -> build/lib/plover/gui_qt
copying plover/gui_qt/add_translation_dialog.py -> build/lib/plover/gui_qt
copying plover/gui_qt/add_translation_widget.py -> build/lib/plover/gui_qt
copying plover/gui_qt/config_serial_widget_ui.py -> build/lib/plover/gui_qt
copying plover/gui_qt/about_dialog.py -> build/lib/plover/gui_qt
copying plover/gui_qt/main.py -> build/lib/plover/gui_qt
copying plover/gui_qt/suggestions_widget.py -> build/lib/plover/gui_qt
copying plover/gui_qt/add_translation_dialog_ui.py -> build/lib/plover/gui_qt
copying plover/gui_qt/resources_rc.py -> build/lib/plover/gui_qt
copying plover/gui_qt/suggestions_dialog_ui.py -> build/lib/plover/gui_qt
copying plover/gui_qt/config_window.py -> build/lib/plover/gui_qt
copying plover/gui_qt/paper_tape_ui.py -> build/lib/plover/gui_qt
copying plover/gui_qt/config_keyboard_widget_ui.py -> build/lib/plover/gui_qt
copying plover/gui_qt/config_file_widget_ui.py -> build/lib/plover/gui_qt
copying plover/gui_qt/lookup_dialog.py -> build/lib/plover/gui_qt
copying plover/gui_qt/dictionary_editor.py -> build/lib/plover/gui_qt
copying plover/gui_qt/suggestions_dialog.py -> build/lib/plover/gui_qt
copying plover/gui_qt/trayicon.py -> build/lib/plover/gui_qt
copying plover/machine/base.py -> build/lib/plover/machine
copying plover/machine/keyboard.py -> build/lib/plover/machine
copying plover/oslayer/xkeyboardcontrol.py -> build/lib/plover/oslayer
copying plover/system/english_stenotype.py -> build/lib/plover/system
copying plover_build_utils/pyqt.py -> build/lib/plover_build_utils
copying plover_build_utils/setup.py -> build/lib/plover_build_utils
copying plover/messages/plover.pot -> build/lib/plover/messages
copying plover/messages/es/LC_MESSAGES/plover.po -> build/lib/plover/messages/es/LC_MESSAGES
copying plover/messages/fr/LC_MESSAGES/plover.po -> build/lib/plover/messages/fr/LC_MESSAGES
copying plover/messages/nl/LC_MESSAGES/plover.po -> build/lib/plover/messages/nl/LC_MESSAGES
copying plover/messages/fr/LC_MESSAGES/plover.mo -> build/lib/plover/messages/fr/LC_MESSAGES
copying plover/messages/nl/LC_MESSAGES/plover.mo -> build/lib/plover/messages/nl/LC_MESSAGES
copying plover/messages/es/LC_MESSAGES/plover.mo -> build/lib/plover/messages/es/LC_MESSAGES
copying plover/gui_qt/add_translation_dialog.ui -> build/lib/plover/gui_qt
copying plover/gui_qt/config_file_widget.ui -> build/lib/plover/gui_qt
copying plover/gui_qt/config_keyboard_widget.ui -> build/lib/plover/gui_qt
copying plover/gui_qt/config_serial_widget.ui -> build/lib/plover/gui_qt
copying plover/gui_qt/dictionaries_widget.ui -> build/lib/plover/gui_qt
copying plover/gui_qt/paper_tape.ui -> build/lib/plover/gui_qt
copying plover/gui_qt/suggestions_dialog.ui -> build/lib/plover/gui_qt
copying plover/gui_qt/suggestions_widget.ui -> build/lib/plover/gui_qt
copying plover_build_utils/functions.sh -> build/lib/plover_build_utils
running build_ext
2021-04-18 20:23:33,157 [MainThread] ERROR: error loading gui.qt.tool plugin: add_translation (from plover.gui_qt.add_translation_dialog)
Traceback (most recent call last):
  File "X/plover/registry.py", line 56, in register_plugin_from_entrypoint
    obj = entrypoint.load()
  File "/home/user202729/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/home/user202729/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "X/plover/gui_qt/add_translation_dialog.py", line 1, in <module>
    from plover.gui_qt.add_translation_dialog_ui import _, Ui_AddTranslationDialog
  File "X/plover/gui_qt/add_translation_dialog_ui.py", line 43, in <module>
    from plover.gui_qt.add_translation_widget import AddTranslationWidget
  File "X/plover/gui_qt/add_translation_widget.py", line 16, in <module>
    from plover.gui_qt.add_translation_widget_ui import _, Ui_AddTranslationWidget
ImportError: cannot import name '_' from 'plover.gui_qt.add_translation_widget_ui' (X/plover/gui_qt/add_translation_widget_ui.py)
2021-04-18 20:23:33,165 [MainThread] ERROR: error loading gui.qt.tool plugin: lookup (from plover.gui_qt.lookup_dialog)
Traceback (most recent call last):
  File "X/plover/registry.py", line 56, in register_plugin_from_entrypoint
    obj = entrypoint.load()
  File "/home/user202729/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/home/user202729/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "X/plover/gui_qt/lookup_dialog.py", line 6, in <module>
    from plover.gui_qt.lookup_dialog_ui import _, Ui_LookupDialog
ImportError: cannot import name '_' from 'plover.gui_qt.lookup_dialog_ui' (X/plover/gui_qt/lookup_dialog_ui.py)
Unexpected error: Traceback (most recent call last):
  File "X/plover/main.py", line 131, in main
    code = gui.main(config)
  File "X/plover/gui_qt/main.py", line 98, in main
    app = Application(config, use_qt_notifications)
  File "X/plover/gui_qt/main.py", line 31, in __init__
    from plover.gui_qt.main_window import MainWindow
  File "X/plover/gui_qt/main_window.py", line 22, in <module>
    from plover.gui_qt.main_window_ui import _, Ui_MainWindow
  File "X/plover/gui_qt/main_window_ui.py", line 196, in <module>
    from plover.gui_qt.dictionaries_widget import DictionariesWidget
  File "X/plover/gui_qt/dictionaries_widget.py", line 30, in <module>
    from plover.gui_qt.dictionary_editor import DictionaryEditor
  File "X/plover/gui_qt/dictionary_editor.py", line 21, in <module>
    from plover.gui_qt.dictionary_editor_ui import _, Ui_DictionaryEditor
ImportError: cannot import name '_' from 'plover.gui_qt.dictionary_editor_ui' (X/plover/gui_qt/dictionary_editor_ui.py)

Exception ignored in: <function Application.__del__ at 0x7f5b874a9040>
Traceback (most recent call last):
  File "X/plover/gui_qt/main.py", line 71, in __del__
    del self._win
AttributeError: _win
```

**Expected behavior**

Should be easy to see.

**Operating system**

- Some Linux distribution..
- Plover Version: See steps to reproduce.

**Comment by benoit-pierre** [comment]
After #1258, you need to ensure UI files are regenerated, use `./setup.py build_ui -f`. (The `.ui` files did not change, but the `gettext` hook used by `build_ui` did).

> I guess setup.py launch is not supported anymore (use tox instead)? Then perhaps that command should be removed?

It's still supported, it's used by `tox -e launch`.

**Comment by user202729** [comment]
For what it's worth, I already figured out a solution with `git clean -fx plover/gui_qt/*_ui.py` or something like that.
