### ISSUE TITLE
Crash on macOS with alternative keyboard layout

### ISSUE THREAD

**Issue by neominik** [openstenoproject/plover#1371]
**Describe the bug**

I am using an alternative keyboard layout for normal typing (neo2, https://dl.neo-layout.org/neo.keylayout). Trying to open Plover for the first time, it crashes with an "Unexpected Error" before I can do anything else:
```
Traceback (most recent call last):
File "/Applications/Plover.app/Contents/Resources/main.py", line 84, in main
File "plover/gui/main.pyc", line 47, in __init__
File "wx/_core.pyc", line 8628, in __init__
File "wx/_core.pyc", line 8196, in _BootstrapApp
File "plover/gui/main.pyc", line 55, in OnInit
File "plover/gui/main.pyc", line 228, in __init__
File "plover/gui/main.pyc", line 368, in __init__
File "plover/oslayer/osxkeyboardcontrol.pyc", line 310, in __init__
File "plover/oslayer/osxkeyboardlayout.pyc", line 128, in __init__
File "plover/oslayer/osxkeyboardlayout.pyc", line 150, in _update_layout
File "plover/oslayer/osxkeyboardlayout.pyc", line 251, in _get_layout
File "plover/oslayer/osxkeyboardlayout.pyc", line 441, in _parse_layout
KeyError: 68
```
Also, when setting the keyboard layout to US, I can start Plover, but as soon as I switch input methods, Plover is immediately gone - without error message…

**To Reproduce**

1. Use keyboard layout file provided at the link above
2. Open Plover

**Expected behavior**

Be able to use Plover, don't crash on launch.

**Operating system**

 - OS: macOS Big Sur 11.4
 - Plover Version 3.1.1 installed via Homebrew

**Hardware**

Keychron K8 TKL mechanical keyboard

**Comment by benoit-pierre** [comment]
I believe this is fixed on master, try the latest development build: https://github.com/openstenoproject/plover/releases/tag/v4.0.0.dev10

**Comment by neominik** [comment]
Indeed it is. Thanks for the quick response!
