### ISSUE TITLE
apostrophe and hyphen keynames not parsing

### ISSUE THREAD

**Issue by jandew42** [openstenoproject/plover#1437]
**Describe the bug**

When I use {#apostrophe} or {#hyphen} for a stroke output, no output is produced. (plover raises an error, see **Log** below)

**To Reproduce**

Assign a new stroke to each of the outputs, e.g.:
```
{
"S": "{#apostrophe}
"T": "{#hyphen}
}
```
then try to type either. No output occurs.

**Expected behavior**

Either an apostrophe or a hypen should be produced by the respectively assigned strokes.

**Log**

I created a log for plover and got this output:

```
ERROR:plover:engine on_stroked failed
Traceback (most recent call last):
  File "build/windist/data\Lib\site-packages\plover\engine.py", line 143, in run
  File "build/windist/data\Lib\site-packages\plover\engine.py", line 379, in _on_stroked
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 207, in translate
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 267, in flush
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 272, in _output
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 452, in format
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 568, in render
  File "build/windist/data\Lib\site-packages\plover\engine.py", line 402, in _send_key_combination
  File "build/windist/data\Lib\site-packages\plover\oslayer\winkeyboardcontrol.py", line 543, in send_key_combination
  File "build/windist/data\Lib\site-packages\plover\key_combo.py", line 177, in parse_key_combo
  File "build/windist/data\Lib\site-packages\plover\key_combo.py", line 157, in _raise_error
ValueError: unknown key in "[hyphen]"
ERROR:plover:engine on_stroked failed
Traceback (most recent call last):
  File "build/windist/data\Lib\site-packages\plover\engine.py", line 143, in run
  File "build/windist/data\Lib\site-packages\plover\engine.py", line 379, in _on_stroked
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 207, in translate
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 267, in flush
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 272, in _output
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 452, in format
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 568, in render
  File "build/windist/data\Lib\site-packages\plover\engine.py", line 402, in _send_key_combination
  File "build/windist/data\Lib\site-packages\plover\oslayer\winkeyboardcontrol.py", line 543, in send_key_combination
  File "build/windist/data\Lib\site-packages\plover\key_combo.py", line 177, in parse_key_combo
  File "build/windist/data\Lib\site-packages\plover\key_combo.py", line 157, in _raise_error
ValueError: unknown key in "[apostrophe]"
```

**Operating system and hardware**

- OS: Windows 10 Home
- Plover: 4.0.0.dev10
- Keyboard: Kumara Redragon K552

**Comment by user202729** [comment]
Intentional. Use `minus` and `shift(8)`.

See also https://github.com/openstenoproject/plover/wiki/Dictionary-Format#shortcut-key-names

**Comment by jandew42** [comment]
Ah, I was using this as my reference, and it's apparently incorrect:
https://sites.google.com/site/learnplover/appendix-the-dictionary-format

**Comment by jandew42** [comment]
Also, `shift(8)` is incorrect, that gives asterisk.
It's not in your linked documentation, but `quoteright` works for apostrophe (though I imagine that's the name for `"` technically)

Which file am I supposed to use as the complete reference for the key names? I found [this one](https://github.com/python-xlib/python-xlib/blob/master/Xlib/keysymdef/latin1.py), but it includes aliases like apostrophe and hyphen which don't actually work :-/

**Comment by user202729** [comment]
Ah yes I misread it.

From the wiki (although I wrote this line)

> instead, an OS-specific function to convert from key name to key code (and return None if the key name is unrecognized) is passed as the second argument of `parse_key_combo`.

I don't use Windows at the moment so I'm not sure if it's hard coded into the code, or dynamically populated based on the current machine configuration.

Perhaps I'll (or someone will) make some plugin to list all the keys, or something better (https://github.com/openstenoproject/plover/issues/1063).

**Comment by morinted** [comment]
Learn Plover has key names from Plover v2. It should be updated.

The [reference file](https://github.com/openstenoproject/plover/blob/master/plover/key_combo.py#L21) is linked in the docs, perhaps it should be made clearer.

May I ask why you're using `{#minus}` instead of simply using `-` or `{^-^}`?

**Comment by user202729** [comment]
@morinted  Yes, that one is linked from the wiki, but as I wrote there https://github.com/openstenoproject/plover/wiki/Dictionary-Format#shortcut-key-names 
it isn't the correct one.

For Windows it's https://github.com/openstenoproject/plover/blob/4394ef158579c1b3088335e3eb7323453fcc0b73/plover/oslayer/winkeyboardlayout.py#L248 (plus some other code to patch it such as https://github.com/openstenoproject/plover/blob/4394ef158579c1b3088335e3eb7323453fcc0b73/plover/oslayer/winkeyboardlayout.py#L444 )

Writing a plugin to get the state dynamically may be the best option, given that it may not even be fixed. But the current API does not expose a portable way.

**Comment by morinted** [comment]
Not exactly right -- the key combo code maps x11-style keynames to Unicode. That list should be accurate for all OS's. Keys that aren't represented in unicode are implemented in the OS-specific files, so key_combo.py is the primary reference list.

**Comment by user202729** [comment]
However most "interesting" keys (page up, make page down, insert, home, etc.) are not in the list because they do not have a (Unicode) character equivalent (if they have a character equivalent then most of the time the user can just {^}character{^}; unless they want it to be non-undoable)

**Comment by morinted** [comment]
I do believe the intent was to use the X11 names -- if we have any inconsistency we should address it.
