### ISSUE TITLE
ERROR: no such script: plover_plugins

### ISSUE THREAD

**Issue by flamenco108** [openstenoproject/plover#1556]
**ERROR: no such script: plover_plugins**

I work on Polish plugin for Plover, so I have local version of this. Right now it installs perfectly on Windows 10 via command: `"C:\Program Files\Open Steno Project\Plover 4.0.0.dev12\plover_console.exe" -s plover_plugins install "D:\Flamenco\GitHub\plover_polish_slowik"`. So I decided to do it on Linux (as below).

Downloaded AppImage on Xubuntu `Linux szmirlap 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux` the latest plover `plover-4.0.0.dev12-x86_64.AppImage` and double clicked. It starts and works.

But it does not allow me to install the plugin. The error message is as above: `ERROR: no such script: plover_plugins`

I checked by `plover -s` and what I get:
```
pelican-plugin-installer 0.1.0:
- pelican-plugin-installer
pip 22.2.2:
- pip
- pip3
- pip3.8
plover 4.0.0.dev12:
- plover
- plover_send_command
pyserial 3.5:
- pyserial-miniterm
- pyserial-ports
spectra-lexer 16.1.0:
- spectra_lexer
```
No `plover_plugins_manager 0.7.0` nor `plover_plugins`

But on gui I see the Plugins Manager and I can use it.

On Windows 10 it is like:
```
pkginfo 1.7.1:
- pkginfo
plover 4.0.0.dev12:
- plover
- plover_send_command
plover-plugins-manager 0.7.0:
- plover_plugins
pyserial 3.5:
- pyserial-miniterm
- pyserial-ports
```

I had also tried to call it directly from AppImage: `flamenco@szmirlap:~/plover_polish_slowik$ ~/bin/Plover/plover-4.0.0.dev12-x86_64.AppImage -s plover_plugins` and got error:
```
Unexpected error: Traceback (most recent call last):
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/scripts/main.py", line 102, in main
  File "/home/flamenco/.config/plover/plugins/linux/lib/python3.9/site-packages/plover_plugins_manager/__main__.py", line 83, in main
    if args[0] == 'list_plugins':
IndexError: list index out of range
```

![2022-08-28_plover-appimage-error](https://user-images.githubusercontent.com/5072952/187068201-f530018e-6f2a-4c1d-835c-e25ed08980aa.png)

**To Reproduce**

1. Go to my local plugin directory
2. Open Terminal
3. Type command: `plover -s plover_plugins install plover_polish_slowik`
4. See error `ERROR: no such script: plover_plugins`

**Expected behavior**

I expected that I will see the output similar to my Windows output:

```
D:\Flamenco\GitHub\plover_polish_slowik>Processing d:\flamenco\github\plover_polish_slowik
  Preparing metadata (setup.py) ... done
Requirement already satisfied: plover>=4.0.0.dev1 in c:\program files\open steno project\plover 4.0.0.dev12\data\lib\site-packages (from plover-polish-slowik==0.0.1) (4.0.0.dev12)
Requirement already satisfied: plover-stroke>=1.1.0 in c:\program files\open steno project\plover 4.0.0.dev12\data\lib\site-packages (from plover>=4.0.0.dev1->plover-polish-slowik==0.0.1) (1.1.0)
Requirement already satisfied: wcwidth in c:\program files\open steno project\plover 4.0.0.dev12\data\lib\site-packages (from plover>=4.0.0.dev1->plover-polish-slowik==0.0.1) (0.2.5)
Requirement already satisfied: setuptools in c:\program files\open steno project\plover 4.0.0.dev12\data\lib\site-packages (from plover>=4.0.0.dev1->plover-polish-slowik==0.0.1) (58.3.0)
Requirement already satisfied: pyserial>=2.7 in c:\program files\open steno project\plover 4.0.0.dev12\data\lib\site-packages (from plover>=4.0.0.dev1->plover-polish-slowik==0.0.1) (3.5)
Requirement already satisfied: rtf-tokenize in c:\program files\open steno project\plover 4.0.0.dev12\data\lib\site-packages (from plover>=4.0.0.dev1->plover-polish-slowik==0.0.1) (1.0.0)
Requirement already satisfied: appdirs>=1.3.0 in c:\program files\open steno project\plover 4.0.0.dev12\data\lib\site-packages (from plover>=4.0.0.dev1->plover-polish-slowik==0.0.1) (1.4.4)
Building wheels for collected packages: plover-polish-slowik
  Building wheel for plover-polish-slowik (setup.py) ... done
  Created wheel for plover-polish-slowik: filename=plover_polish_slowik-0.0.1-py3-none-any.whl size=4578 sha256=3b9b31f65d79f96881c280a22c7f777f8005f44f3548fadedf34e2dba76ef06e
  Stored in directory: C:\Users\flamenco\AppData\Local\Temp\pip-ephem-wheel-cache-k1pkxlhn\wheels\d0\51\fc\8d9bfac5d82151fb78d12d62c5950ef03e04cf8c7a4ff9d666
Successfully built plover-polish-slowik
Installing collected packages: plover-polish-slowik
Successfully installed plover-polish-slowik-0.0.1
```

And I will have the plugin installed.

**Screenshots**

![2022-08-28_plover-plugin-manag](https://user-images.githubusercontent.com/5072952/187068623-f0114689-b88d-47ce-b0d9-02cfbf51f48f.png)

**Operating system**

 - OS: Linux `szmirlap 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
 - Plover Version: `plover-4.0.0.dev12-x86_64.AppImage` 

**Hardware**

*If applicable, let us know what machine you're experiencing the issue with and how it's connected to Plover, as well as a screenshot of the machine configuration inside Plover.*

It is an old laptop Dell Latitude 3540, RAM 8GB, Intel CPU core I-5, SSD, with sticker "Adapted to Ubuntu"

***$ plover -l info***
```
$ plover -l info
2022-08-28 12:14:07,134 [MainThread] INFO: Plover 4.0.0.dev12
2022-08-28 12:14:07,135 [MainThread] INFO: configuration directory: /home/flamenco/.config/plover
2022-08-28 12:14:07,336 [MainThread] INFO: command: set_config (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,347 [MainThread] INFO: dictionary: json (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,356 [MainThread] INFO: dictionary: rtf (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,358 [MainThread] INFO: extension: alleycat_link (from alleycat-link 0.4.4 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,363 [MainThread] INFO: gui: none (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,365 [MainThread] INFO: gui: qt (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,367 [MainThread] INFO: gui.qt.machine_option: plover.machine.base:SerialStenotypeBase (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,374 [MainThread] INFO: gui.qt.machine_option: plover.machine.keyboard:Keyboard (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,375 [MainThread] INFO: gui.qt.tool: add_translation (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,381 [MainThread] INFO: gui.qt.tool: lookup (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,383 [MainThread] INFO: gui.qt.tool: paper_tape (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,386 [MainThread] INFO: gui.qt.tool: suggestions (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,388 [MainThread] INFO: gui.qt.tool: lexer_plugin (from spectra-lexer 16.1.0 in /usr/local/lib/python3.8/dist-packages/spectra_lexer-16.1.0-py3.8.egg)
2022-08-28 12:14:07,431 [MainThread] INFO: machine: Gemini PR (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,433 [MainThread] INFO: machine: Keyboard (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,434 [MainThread] INFO: machine: Passport (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,436 [MainThread] INFO: machine: ProCAT (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,437 [MainThread] INFO: machine: Stentura (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,439 [MainThread] INFO: machine: TX Bolt (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,441 [MainThread] INFO: macro: repeat_last_stroke (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,443 [MainThread] INFO: macro: retrospective_delete_space (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,444 [MainThread] INFO: macro: retrospective_insert_space (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,446 [MainThread] INFO: macro: retrospective_toggle_asterisk (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,447 [MainThread] INFO: macro: undo (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,450 [MainThread] INFO: meta: attach (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,452 [MainThread] INFO: meta: carry_capitalize (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,453 [MainThread] INFO: meta: case (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,455 [MainThread] INFO: meta: comma (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,457 [MainThread] INFO: meta: command (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,458 [MainThread] INFO: meta: glue (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,460 [MainThread] INFO: meta: if_next_matches (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,461 [MainThread] INFO: meta: key_combo (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,463 [MainThread] INFO: meta: mode (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,464 [MainThread] INFO: meta: retro_case (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,466 [MainThread] INFO: meta: retro_currency (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,467 [MainThread] INFO: meta: stop (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,468 [MainThread] INFO: meta: word_end (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,470 [MainThread] INFO: system: English Stenotype (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:14:07,472 [MainThread] INFO: another instance is running, sending `focus` command
```

```
flamenco@szmirlap:~/Tera/GIT/plover_polish_slowik$ plover -l error
flamenco@szmirlap:~/Tera/GIT/plover_polish_slowik$ plover -l warning
flamenco@szmirlap:~/Tera/GIT/plover_polish_slowik$ plover -l debug
2022-08-28 12:20:19,550 [MainThread] INFO: Plover 4.0.0.dev12
2022-08-28 12:20:19,550 [MainThread] INFO: configuration directory: /home/flamenco/.config/plover
2022-08-28 12:20:19,724 [MainThread] INFO: command: set_config (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,736 [MainThread] INFO: dictionary: json (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,746 [MainThread] INFO: dictionary: rtf (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,749 [MainThread] INFO: extension: alleycat_link (from alleycat-link 0.4.4 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,755 [MainThread] INFO: gui: none (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,758 [MainThread] INFO: gui: qt (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,760 [MainThread] INFO: gui.qt.machine_option: plover.machine.base:SerialStenotypeBase (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,767 [MainThread] INFO: gui.qt.machine_option: plover.machine.keyboard:Keyboard (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,769 [MainThread] INFO: gui.qt.tool: add_translation (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,774 [MainThread] INFO: gui.qt.tool: lookup (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,777 [MainThread] INFO: gui.qt.tool: paper_tape (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,780 [MainThread] INFO: gui.qt.tool: suggestions (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,782 [MainThread] INFO: gui.qt.tool: lexer_plugin (from spectra-lexer 16.1.0 in /usr/local/lib/python3.8/dist-packages/spectra_lexer-16.1.0-py3.8.egg)
2022-08-28 12:20:19,831 [MainThread] INFO: machine: Gemini PR (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,834 [MainThread] INFO: machine: Keyboard (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,836 [MainThread] INFO: machine: Passport (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,837 [MainThread] INFO: machine: ProCAT (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,839 [MainThread] INFO: machine: Stentura (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,841 [MainThread] INFO: machine: TX Bolt (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,842 [MainThread] INFO: macro: repeat_last_stroke (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,845 [MainThread] INFO: macro: retrospective_delete_space (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,847 [MainThread] INFO: macro: retrospective_insert_space (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,848 [MainThread] INFO: macro: retrospective_toggle_asterisk (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,849 [MainThread] INFO: macro: undo (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,851 [MainThread] INFO: meta: attach (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,854 [MainThread] INFO: meta: carry_capitalize (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,856 [MainThread] INFO: meta: case (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,857 [MainThread] INFO: meta: comma (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,859 [MainThread] INFO: meta: command (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,860 [MainThread] INFO: meta: glue (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,861 [MainThread] INFO: meta: if_next_matches (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,864 [MainThread] INFO: meta: key_combo (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,865 [MainThread] INFO: meta: mode (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,867 [MainThread] INFO: meta: retro_case (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,868 [MainThread] INFO: meta: retro_currency (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,870 [MainThread] INFO: meta: stop (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,872 [MainThread] INFO: meta: word_end (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,874 [MainThread] INFO: system: English Stenotype (from plover 4.0.0.dev12 in /usr/local/lib/python3.8/dist-packages)
2022-08-28 12:20:19,877 [MainThread] INFO: another instance is running, sending `focus` command
```

I don't know, what else to put in here.

Please, help.

**Comment by benoit-pierre** [comment]
It looks you have 2 different versions of Plover installed: the AppImage (in `~/bin/Plover`), and another version (in `/usr/local/lib/python3.8/dist-packages`).

To install your plugin for the AppImage version, use: `~/bin/Plover/plover-4.0.0.dev12-x86_64.AppImage -s plover_plugins install […]/plover_polish_slowik` (with the full path to your plugin source directory).
