### ISSUE TITLE
`AttributeError` when changing protocol or pressing reconnect button

### ISSUE THREAD

**Issue by mhmdanas** [openstenoproject/plover#1638]
**Describe the bug**

Whenever I press on the button labeled "Disconnect and reconnect the machine," or change the protocol (e.g. from "Gemini PR" to "Keyboard"), Plover notifies me that there was an error and prints a stack trace:

```
2023-10-02 18:40:58,312 [Dummy-1] ERROR: engine update failed
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/plover/engine.py", line 147, in run
    if func(*args, **kwargs):
       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/plover/engine.py", line 214, in _update
    self._keyboard_emulation.set_key_press_delay(config['time_between_key_presses'])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'KeyboardEmulation' object has no attribute 'set_key_press_delay'
```

This happens regardless of whether my Uni is connected.

**To Reproduce**

1. Switch protocol, or press on reconnect button
2. See error

**Expected behavior**

No errors happen.

**Operating system**

 - OS: [e.g. Windows 10, Ubuntu 20.04, macOS Catalina] Void Linux
 - Plover Version [e.g. 3.x, 4.x, weekly] 4.0.0rc2

It's worth noting that this issue doesn't happen on 4.0.0rc1 or earlier versions.

**Hardware**

Not appliacable probably, but it's a Uni 4 connected via Gemini PR. Here's the machine configuration:

![Picture of my machine configuration in Plover](https://github.com/openstenoproject/plover/assets/32234660/f5b44fe3-c1f1-4c8e-ac9c-79491cab5654)

**Comment by mhmdanas** [comment]
I ended up narrowing down the issue to `plover-wtype-output`, as the error disappears when I start Plover with it disabled. I'll see if I can fix it or at least report it to the plugin author.
