### ISSUE TITLE
Plugin Manager disappeared (pkg_resources.ContextualVersionConflict: attrs 23.2.0)

### ISSUE THREAD

**Issue by lynn** [openstenoproject/plover#1653]
**Describe your issue**

After installing and uninstalling [plover_layout_display](https://github.com/morinted/plover_layout_display/), the Plugin Manager button disappeared from the Plover UI.

If I try to manage my plugins from the command line...

```
PS C:\Program Files\Open Steno Project\Plover 4.0.0rc2> .\plover_console.exe -l debug -s plover_plugins
```

I get strange errors:

```
2024-01-16 20:28:17,074 [MainThread] INFO: could not import platform gui log
Traceback (most recent call last):
  File "build/windist/data\Lib\site-packages\plover\log.py", line 87, in setup_platform_handler
  File "build/windist/data\Lib\site-packages\plover\oslayer\windows\log.py", line 1, in <module>
ModuleNotFoundError: No module named 'plover.log_plyer'
2024-01-16 20:28:17,075 [MainThread] INFO: Plover 4.0.0rc2
2024-01-16 20:28:17,075 [MainThread] INFO: configuration directory: C:\Users\lynn\AppData\Local\plover\plover
2024-01-16 20:28:17,196 [MainThread] INFO: command: end_solo_dict (from plover-dict-commands 0.2.5 in c:\users\lynn\appdata\local\plover\plover\plugins\win\python39\site-packages)
2024-01-16 20:28:17,198 [MainThread] INFO: command: priority_dict (from plover-dict-commands 0.2.5 in c:\users\lynn\appdata\local\plover\plover\plugins\win\python39\site-packages)
2024-01-16 20:28:17,199 [MainThread] INFO: command: solo_dict (from plover-dict-commands 0.2.5 in c:\users\lynn\appdata\local\plover\plover\plugins\win\python39\site-packages)
2024-01-16 20:28:17,200 [MainThread] INFO: command: toggle_dict (from plover-dict-commands 0.2.5 in c:\users\lynn\appdata\local\plover\plover\plugins\win\python39\site-packages)
2024-01-16 20:28:17,204 [MainThread] INFO: command: set_config (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,207 [MainThread] INFO: dictionary: py (from plover-python-dictionary 1.1.0 in c:\users\lynn\appdata\local\plover\plover\plugins\win\python39\site-packages)
2024-01-16 20:28:17,211 [MainThread] INFO: dictionary: json (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,213 [MainThread] INFO: dictionary: rtf (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,216 [MainThread] INFO: extension: plover_fancytext (from plover-fancytext 1.9.0 in c:\users\lynn\appdata\local\plover\plover\plugins\win\python39\site-packages)
2024-01-16 20:28:17,237 [MainThread] INFO: extension: plover_clippy_2 (from plover-clippy-2 0.0.5 in c:\users\lynn\appdata\local\plover\plover\plugins\win\python39\site-packages)
2024-01-16 20:28:17,260 [MainThread] INFO: gui: none (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,263 [MainThread] INFO: gui: qt (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,264 [MainThread] INFO: gui.qt.machine_option: plover.machine.base:SerialStenotypeBase (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,275 [MainThread] INFO: gui.qt.machine_option: plover.machine.keyboard:Keyboard (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,276 [MainThread] INFO: gui.qt.tool: lexer_plugin (from spectra-lexer 16.1.0 in c:\users\lynn\appdata\local\plover\plover\plugins\win\python39\site-packages)
2024-01-16 20:28:17,334 [MainThread] INFO: gui.qt.tool: plugins_manager (from plover-plugins-manager 0.7.1 in c:\users\lynn\appdata\local\plover\plover\plugins\win\python39\site-packages)
2024-01-16 20:28:17,424 [MainThread] ERROR: error loading gui.qt.tool plugin: plugins_manager (from plover_plugins_manager.gui_qt.manager)
Traceback (most recent call last):
  File "build/windist/data\Lib\site-packages\plover\registry.py", line 55, in register_plugin_from_entrypoint
  File "build/windist/data\Lib\site-packages\pkg_resources\__init__.py", line 2449, in load
  File "build/windist/data\Lib\site-packages\pkg_resources\__init__.py", line 2472, in require
  File "build/windist/data\Lib\site-packages\pkg_resources\__init__.py", line 777, in resolve
pkg_resources.ContextualVersionConflict: (attrs 23.2.0 (c:\users\lynn\appdata\local\plover\plover\plugins\win\python39\site-packages), Requirement.parse('attrs<22.0,>=21.2'), {'requests-cache'})
2024-01-16 20:28:17,425 [MainThread] INFO: gui.qt.tool: add_translation (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,430 [MainThread] INFO: gui.qt.tool: lookup (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,432 [MainThread] INFO: gui.qt.tool: paper_tape (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,438 [MainThread] INFO: gui.qt.tool: suggestions (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,440 [MainThread] INFO: machine: Gemini PR (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,442 [MainThread] INFO: machine: Keyboard (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,443 [MainThread] INFO: machine: Passport (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,444 [MainThread] INFO: machine: ProCAT (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,445 [MainThread] INFO: machine: Stentura (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,446 [MainThread] INFO: machine: TX Bolt (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,447 [MainThread] INFO: machine: Treal (from plover-treal 1.0.1 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,455 [MainThread] INFO: macro: repeat_last_stroke (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,457 [MainThread] INFO: macro: retrospective_delete_space (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,458 [MainThread] INFO: macro: retrospective_insert_space (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,458 [MainThread] INFO: macro: retrospective_toggle_asterisk (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,459 [MainThread] INFO: macro: undo (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,460 [MainThread] INFO: meta: fancytext_retro (from plover-fancytext 1.9.0 in c:\users\lynn\appdata\local\plover\plover\plugins\win\python39\site-packages)
2024-01-16 20:28:17,461 [MainThread] INFO: meta: attach (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,463 [MainThread] INFO: meta: carry_capitalize (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,464 [MainThread] INFO: meta: case (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,464 [MainThread] INFO: meta: comma (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,466 [MainThread] INFO: meta: command (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,468 [MainThread] INFO: meta: glue (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,470 [MainThread] INFO: meta: if_next_matches (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,471 [MainThread] INFO: meta: key_combo (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,472 [MainThread] INFO: meta: mode (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,474 [MainThread] INFO: meta: retro_case (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,474 [MainThread] INFO: meta: retro_currency (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,475 [MainThread] INFO: meta: stop (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,476 [MainThread] INFO: meta: word_end (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
2024-01-16 20:28:17,477 [MainThread] INFO: system: Stenotype Extended (from plover-stenotype-extended 1.0.0 in c:\users\lynn\appdata\local\plover\plover\plugins\win\python39\site-packages)
2024-01-16 20:28:17,480 [MainThread] INFO: system: English Stenotype (from plover 4.0.0rc2 in c:\program files\open steno project\plover 4.0.0rc2\data\lib\site-packages)
Unexpected error: Traceback (most recent call last):
  File "build/windist/data\Lib\site-packages\plover\scripts\main.py", line 102, in main
  File "build/windist/data\Lib\site-packages\pkg_resources\__init__.py", line 2449, in load
  File "build/windist/data\Lib\site-packages\pkg_resources\__init__.py", line 2472, in require
  File "build/windist/data\Lib\site-packages\pkg_resources\__init__.py", line 777, in resolve
pkg_resources.ContextualVersionConflict: (attrs 23.2.0 (c:\users\lynn\appdata\local\plover\plover\plugins\win\python39\site-packages), Requirement.parse('attrs<22.0,>=21.2'), {'requests-cache'})
```

**Steps you've taken**

I've upgraded from 4.0.0dev12 to 4.0.0rc2 but the issue remained.

**Screenshots**

The Plugin Manager used to be to the right of "Suggestions".

![image](https://github.com/openstenoproject/plover/assets/16232127/febb6f8f-d5a2-42e4-8e64-995fe6e7ad55)

**Operating system**

 - OS: Windows 10
 - Plover Version 4.0.0rc2

**Comment by user202729** [comment]
How problematic. It is sort of by-design that a Python environment can only have one version of a package (unlike e.g. Node.js), and Plover will not start if there's a package version conflict/missing dependency (I'm not sure if this is a feature or a bug)

#1524:

> even manually install plugins through plover_plugins does not work

In any case, the easy option is to uninstall Plover completely and reinstall it. (you'll need to reinstall plugins though, the dictionaries and configuration should not be deleted... but keep a backup just in case?)

The hard option would be something like running `C:\Program Files\Open Steno Project\Plover 4.0.0rc2\bin\python -m pip install attrs==21.2` (I'm not sure what is the path to `python` executable exactly, search in the directory) to fix the version of that package, or just `pip install -U` to upgrade everything to the latest version which should work as well.

**Comment by lynn** [comment]
I ended up completely reinstalling Plover.
