### ISSUE TITLE
(Chrome OS) Keyboard output is enabled, but default qwerty output is shown in other apps

### ISSUE THREAD

**Issue by actlists** [openstenoproject/plover#1662]
**Describe the bug**

When I try to enable the keyboard, it shows the output on the paper tape correctly, but it doesn't output to other applications.

**To Reproduce**

1. Go to Tools
2. Click on Paper Tape
3. See that the output is correct
4. Go to other program
5. Try to type
6. Shows the output in qwerty format.

**Expected behavior**

I expected the output from the paper tape to be shown on other applications

**Operating system**

 - OS: Chrome OS with Linux installed
 - Plover Version: 4.0

**Hardware**

Machine - Lenovo 100e Chromebook

**Comment by actlists** [comment]
Another thing to note is that the debug log shows this error:
`2024-02-12 14:24:06,390 [MainThread] INFO: could not initialize platform gui log
Traceback (most recent call last):
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/log.py", line 92, in setup_platform_handler
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/oslayer/linux/log_dbus.py", line 147, in __init__
ConnectionError: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-747eaJXP9I: Connection refused`

**Comment by Spentine** [comment]
If you haven't done it, did you press the refresh icon in the 'Machine' box? 
![image](https://github.com/openstenoproject/plover/assets/114318049/22a16edc-4246-4e26-85f0-e9039a77777a)

**Comment by aerickt** [comment]
Is this using the Linux Development Environment?

**Comment by ethanporcaro** [comment]
If you're using the Linux development environment, then plover will only output to other programs running there. Meaning you can't use Chrome or other ChromeOS apps unless you also install them under Linux.
