### ISSUE TITLE
error on line 72 keyError qt

### ISSUE THREAD

**Issue by Kiwi-the-Cat** [openstenoproject/plover#1685]
When I attempt to start Plover I get an error

I've updated everything, made sure I have all the libraries, and looked on the internet for an answer

I expect Plover to launch without throwing an error

**Expected behavior**
```
Traceback (most recent call last):
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/runpy.py", line 87, in _run_code
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/scripts/main.py", line 170, in <module>
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/scripts/main.py", line 76, in main
  File "/home/runner/work/plover/plover/build/appimage/plover.AppDir/usr/lib/python3.9/site-packages/plover/registry.py", line 72, in get_plugin
KeyError: 'qt'
```

Pop!_OS 22.04 LTS

 - OS: [e.g. Windows 10, Ubuntu 20.04, macOS Catalina]
 - Plover Version [e.g. 3.x, 4.x, weekly]

**Hardware**

If applicable, let us know what machine you're experiencing the issue with and how it's connected to Plover, as well as a screenshot of the machine configuration inside Plover.

**Comment by domoriga** [comment]
Perhaps you're missing an interface to glib thread abstraction? 
Try installing 'libgthread*' from your distro's repo and see if that resolves your issue.
HTH

**Comment by wmealing** [comment]
I've been trying to build this on apple silicon and are getting to this very same point when building from the git tree.

**Comment by androclus** [comment]
Thank you @domoriga .  I was getting exact same (frustrating) error message as OP @Kiwi-the-Cat .. 

Taking your suggestion, on my OpenSUSE (Tumbleweed) system, I ran:

`$ sudo zypper in libgthread-2_0-0`

and now the .AppImage runs

Seems to me a simple, "Try installing libgthread" error message instead of above cryptic error msg would save a few earth cycles (?)

**Comment by wmealing** [comment]
Not sure what the issue was, i had to re-install qt@5 with brew.

brew install qt@5
