### ISSUE TITLE
Crash on startup: KeyError: 8 (Czech keyboard)

### ISSUE THREAD

**Issue by Meldiron** [openstenoproject/plover#1689]
**Describe the bug**

When launching the app while having Czech keyboard active, the app crashes. Starting it with english keyboard works fine, but when running an I switch to Czech, it instantly crashes.

**To Reproduce**

1. Use Czech layout (MacOS)
2. Start Plover
3. (crash)

**Expected behavior**

Plover works with czech layout too (or disables, but starts working again after switching back  to english layout.

**Screenshots**

![CleanShot 2024-09-13 at 11 04 11@2x](https://github.com/user-attachments/assets/eee91664-bfb7-43f1-996b-33753228007a)

```
Traceback (most recent call last):
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.9/site-packages/plover/scripts/main.py", line 131, in main
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.9/site-packages/plover/gui_qt/main.py", line 129, in main
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.9/site-packages/plover/gui_qt/main.py", line 67, in __init__
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.9/site-packages/plover/oslayer/osx/keyboardcontrol.py", line 311, in __init__
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.9/site-packages/plover/oslayer/osx/keyboardlayout.py", line 130, in __init__
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.9/site-packages/plover/oslayer/osx/keyboardlayout.py", line 152, in _update_layout
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.9/site-packages/plover/oslayer/osx/keyboardlayout.py", line 260, in _get_layout
  File "/Users/runner/work/plover/plover/build/osxapp/Plover.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.9/site-packages/plover/oslayer/osx/keyboardlayout.py", line 411, in _parse_layout
KeyError: 8
```

Crash report: (can provide if requested, they are huge)

**Operating system**

- MacOS 14.5 (23F79)
- Plover 4.0.0rc2 

**Hardware**

Macbook Pro 2021

**Comment by skanev** [comment]
So I have the same problem, and the bottom line is that the code in `KeyboardLayout` for macOS is buggy. It works OK if you are switching from (say) Qwerty to Dvorak, but if one of your layouts is not, bummer. I tried to fix it, but sadly, I can't build Plover locally (yet).

I did however, manage to build it via the GitHub actions, tested it, and it actually works. That's the reason I'm writing here – if you're interested, you can download a build [from here](https://github.com/skanev/plover/actions/runs/14148492003). Keep in mind that you have to be in English when you start Plover.

Hopefully they (or I) will fix this issue upstream.
