### ISSUE TITLE
Installed Plover has UTF-8 error when creating default dictionary

### ISSUE THREAD

**Issue by ezyang** [openstenoproject/plover#220]
Steps to reproduce:

1. Move your ~/.local/share/plover somewhere (e.g. plover.bak), to force Plover to initialize a default dictionary
2. `sudo python setup.py install` the most recent Git version of Plover
3. Run Plover from the globally installed version

You will get this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/plover/main.py", line 72, in main
    init_config_dir()
  File "/usr/local/lib/python2.7/dist-packages/plover/main.py", line 55, in init_config_dir
    unified_dict.update(json.load(open(dict_filename, 'rb')))
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf7 in position 0: invalid start byte
```

The error doesn't seem to occur if you run directly out of the Git checkout, and once the dictionary is initialized Plover works fine

**Comment by morinted** [comment]
Is it possible to confirm this? Not sure if this is still true.

**Comment by morinted** [comment]
We load UTF-8 by default now, this may be fixed. I'll close this issue since it hasn't seemed to come up for a while.
