### ISSUE TITLE
IOError: [Errno 10] Keine Kind-Prozesse

### ISSUE THREAD

**Issue by hhirsch** [openstenoproject/plover#231]
Traceback (most recent call last):
  File "/usr/local/bin/plover", line 23, in <module>
    gui = plover.gui.main.PloverGUI()
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/plover/gui/main.py", line 32, in OnInit
    frame = Frame(conf.CONFIG_FILE)
  File "/usr/local/lib/python2.7/dist-packages/plover/gui/main.py", line 70, in __init__
    self.steno_engine = app.StenoEngine()
  File "/usr/local/lib/python2.7/dist-packages/plover/app.py", line 142, in __init__
    self.machine = self.machine_module.Stenotype(**self.machine_init)
  File "/usr/local/lib/python2.7/dist-packages/plover/machine/sidewinder.py", line 61, in __init__
    self._keyboard_emulation = keyboardcontrol.KeyboardEmulation()
  File "/usr/local/lib/python2.7/dist-packages/plover/keyboardcontrol.py", line 159, in __init__
    self.display = display.Display()
  File "/usr/lib/pymodules/python2.7/Xlib/display.py", line 83, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/pymodules/python2.7/Xlib/display.py", line 65, in __init__
    apply(protocol.display.Display.__init__, (self, ) + args, keys)
  File "/usr/lib/pymodules/python2.7/Xlib/protocol/display.py", line 44, in __init__
    name, host, displayno, screenno = connect.get_display(display)
  File "/usr/lib/pymodules/python2.7/Xlib/support/connect.py", line 64, in get_display
    mod = __import__(modname, globals())
  File "/usr/lib/pymodules/python2.7/Xlib/support/unix_connect.py", line 43, in <module>
    uname = platform.uname()
  File "/usr/lib/python2.7/platform.py", line 1273, in uname
    processor = _syscmd_uname('-p','')
  File "/usr/lib/python2.7/platform.py", line 1030, in _syscmd_uname
    rc = f.close()
IOError: [Errno 10] Keine Kind-Prozesse

**Comment by balshetzer** [comment]
Can you provide more information?

**Comment by hhirsch** [comment]
I just installed by pip and launched plover and all I
got was this trace. I am on Debian 7 on xmonad. The trace seems to indicate that there was a problem launching uname as a child process.  And when I try running uname -p I get unknown. Maybe that normal and documented behaviour is considered exceptional by platform.py. But I am just throwing spaghetti at the wall seeing what sticks. Thank you for looking into this and tell me if you need more information and I go probe my system.

**Comment by hhirsch** [comment]
When following http://openstenoproject.github.io/plover/ I get the same error.

**Comment by balshetzer** [comment]
The version of Plover that is installed by pip is very old. Also, installing Plover with pip doesn't install its dependencies.

I see you found the newer instructions. I assume you downloaded the new code, installed all the specified dependencies and still get the error?

**Comment by hhirsch** [comment]
Yes, only difference is that the message is displayed in a gtk window.

**Comment by balshetzer** [comment]
Can you find out which version of python2.7 you're using?

**Comment by hhirsch** [comment]
Python 2.7.3

**Comment by balshetzer** [comment]
One thing we could try is updating to a newer version. It goes up to 2.7.9 now.

**Comment by hhirsch** [comment]
It works with my work PC with the same OS and python.

**Comment by balshetzer** [comment]
Can you think of some way in which the two computers are different?

**Comment by hhirsch** [comment]
No, I assumed we could get insights from the trace.

**Comment by hhirsch** [comment]
I commented out Line 1273 and the next.
    #if not processor:  
        # Get processor information from the uname system command                     
        # processor = _syscmd_uname('-p','') 

In /usr/lib/python2.7/platform.py
and now plover starts.

Can you check if your platform.py is different there?

**Comment by balshetzer** [comment]
I downloaded the source for Python 2.7.3 and it does not match. I'm not sure what that means. 

A simpler thing to test would be to restore your platform.py to its original form, open a console and enter:
import platform; platform.uname()

Does it throw an exception?

**Comment by hhirsch** [comment]
I assume this issue has nothing to do with plover. I will re-open it if I have reason to assume it is plovers fault.
