### ISSUE TITLE
weekly-v137 Install error Ubuntu 14.04

### ISSUE THREAD

**Issue by bmsleight** [openstenoproject/plover#417]
Classification: Crash

Reproducibility: Always

## Summary
weekly-v137 does not run 
although I not installed other weeks

Summary of the problem.
```
bms@FortBoyard:~$ sudo pip install https://github.com/openstenoproject/plover/releases/download/weekly-v137/Plover-2.5.8.317.gced379f-py2-none-any.whl
Downloading/unpacking https://github.com/openstenoproject/plover/releases/download/weekly-v137/Plover-2.5.8.317.gced379f-py2-none-any.whl
  Downloading Plover-2.5.8.317.gced379f-py2-none-any.whl (2.2MB): 2.2MB downloaded
Requirement already satisfied (use --upgrade to upgrade): wxPython>=3.0 in /usr/lib/python2.7/dist-packages/wx-3.0-gtk2 (from Plover==2.5.8-317.gced379f)
Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from Plover==2.5.8-317.gced379f)
Requirement already satisfied (use --upgrade to upgrade): python-xlib>=0.14 in /usr/lib/python2.7/dist-packages (from Plover==2.5.8-317.gced379f)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from Plover==2.5.8-317.gced379f)
Requirement already satisfied (use --upgrade to upgrade): pyserial>=2.7 in /usr/local/lib/python2.7/dist-packages (from Plover==2.5.8-317.gced379f)
Downloading/unpacking hidapi (from Plover==2.5.8-317.gced379f)
  Downloading hidapi-0.7.99.post14.tar.gz
  Running setup.py (path:/tmp/pip_build_root/hidapi/setup.py) egg_info for package hidapi
    
Requirement already satisfied (use --upgrade to upgrade): Cython in /usr/lib/python2.7/dist-packages (from hidapi->Plover==2.5.8-317.gced379f)
Installing collected packages: Plover, hidapi
  Running setup.py install for hidapi
    cythoning hid.pyx to hid.c
    building 'hid' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ihidapi/hidapi -I/usr/include/libusb-1.0 -I/usr/include/python2.7 -c hid.c -o build/temp.linux-x86_64-2.7/hid.o
    hid.c: In function ‘__pyx_pf_3hid_6device_open’:
    hid.c:1475:7: warning: passing argument 1 of ‘PyUnicodeUCS4_AsWideChar’ from incompatible pointer type [enabled by default]
           __pyx_v_result = PyUnicode_AsWideChar(__pyx_v_serial_number, __pyx_v_cserial_number, __pyx_v_serial_len);
           ^
    In file included from /usr/include/python2.7/Python.h:85:0,
                     from hid.c:16:
    /usr/include/python2.7/unicodeobject.h:246:31: note: expected ‘struct PyUnicodeObject *’ but argument is of type ‘struct PyObject *’
     # define PyUnicode_AsWideChar PyUnicodeUCS4_AsWideChar
                                   ^
    /usr/include/python2.7/unicodeobject.h:591:24: note: in expansion of macro ‘PyUnicode_AsWideChar’
     PyAPI_FUNC(Py_ssize_t) PyUnicode_AsWideChar(
                            ^
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ihidapi/hidapi -I/usr/include/libusb-1.0 -I/usr/include/python2.7 -c hidapi/libusb/hid.c -o build/temp.linux-x86_64-2.7/hidapi/libusb/hid.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/hid.o build/temp.linux-x86_64-2.7/hidapi/libusb/hid.o -lusb-1.0 -ludev -lrt -o build/lib.linux-x86_64-2.7/hid.so
    cythoning hidraw.pyx to hidraw.c
    building 'hidraw' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ihidapi/hidapi -I/usr/include/python2.7 -c hidraw.c -o build/temp.linux-x86_64-2.7/hidraw.o
    hidraw.c: In function ‘__pyx_pf_6hidraw_6device_open’:
    hidraw.c:1475:7: warning: passing argument 1 of ‘PyUnicodeUCS4_AsWideChar’ from incompatible pointer type [enabled by default]
           __pyx_v_result = PyUnicode_AsWideChar(__pyx_v_serial_number, __pyx_v_cserial_number, __pyx_v_serial_len);
           ^
    In file included from /usr/include/python2.7/Python.h:85:0,
                     from hidraw.c:16:
    /usr/include/python2.7/unicodeobject.h:246:31: note: expected ‘struct PyUnicodeObject *’ but argument is of type ‘struct PyObject *’
     # define PyUnicode_AsWideChar PyUnicodeUCS4_AsWideChar
                                   ^
    /usr/include/python2.7/unicodeobject.h:591:24: note: in expansion of macro ‘PyUnicode_AsWideChar’
     PyAPI_FUNC(Py_ssize_t) PyUnicode_AsWideChar(
                            ^
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ihidapi/hidapi -I/usr/include/python2.7 -c hidapi/linux/hid.c -o build/temp.linux-x86_64-2.7/hidapi/linux/hid.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/hidraw.o build/temp.linux-x86_64-2.7/hidapi/linux/hid.o -ludev -lrt -o build/lib.linux-x86_64-2.7/hidraw.so
    
Successfully installed Plover hidapi
Cleaning up...
bms@FortBoyard:~$ plover 
Traceback (most recent call last):
  File "/usr/local/bin/plover", line 7, in <module>
    from plover.main import main
  File "/usr/local/lib/python2.7/dist-packages/plover/main.py", line 20, in <module>
    import plover.gui.main
  File "/usr/local/lib/python2.7/dist-packages/plover/gui/main.py", line 17, in <module>
    import plover.app as app
  File "/usr/local/lib/python2.7/dist-packages/plover/app.py", line 21, in <module>
    import plover.config as conf
  File "/usr/local/lib/python2.7/dist-packages/plover/config.py", line 12, in <module>
    from plover.machine.registry import machine_registry
  File "/usr/local/lib/python2.7/dist-packages/plover/machine/registry.py", line 6, in <module>
    from plover.machine.geminipr import Stenotype as geminipr
  File "/usr/local/lib/python2.7/dist-packages/plover/machine/geminipr.py", line 6, in <module>
    import plover.machine.base
  File "/usr/local/lib/python2.7/dist-packages/plover/machine/base.py", line 14, in <module>
    from plover import system
ImportError: cannot import name system
bms@FortBoyard:~$ 

```

## Steps to Reproduce

```
bms@FortBoyard:~$ head -n 1  /etc/apt/sources.list 
# deb cdrom:[Ubuntu 14.04.1 LTS _Trusty Tahr_ - Release amd64 (20140722.2)]/ trusty main restricted
bms@FortBoyard:~$ uname -a
Linux FortBoyard 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
bms@FortBoyard:~$

```
Plover version weekly-v137

**Comment by morinted** [comment]
Thanks Brendan. This will be fixed in the next weekly (incoming soon)

**Comment by morinted** [comment]
Should be fixed with https://github.com/openstenoproject/plover/releases/tag/weekly-v2.5.8%2B456.g56f1410

Reopen if you can't get it working!

**Comment by bmsleight** [comment]
Confirmed fixed, Thanks Ted.

**Comment by morinted** [comment]
Cheers, but it's all @Benoit-Pierre!
