### ISSUE TITLE
Dictionary Editor crashes when searching for something or only allows one search

### ISSUE THREAD

**Issue by percidae** [openstenoproject/plover#540]
I am (mostly) using Plover from the ppa from @benoit-pierre on LMDE, my input device is a Stentura 400 SRT.
When I try to filter in the dictionary editor it crashes Plover. It doesn't matter if I filter for a stroke or a translation.

This is the output in the terminal I got, when I started it from there:
```
myusername@shuttle:~$ plover
Xlib.protocol.request.QueryExtension
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/usr/lib/python2.7/dist-packages/plover/dictionary_editor_store.py", line 70, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/usr/lib/python2.7/dist-packages/plover/dictionary_editor_store.py", line 70, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/usr/lib/python2.7/dist-packages/plover/dictionary_editor_store.py", line 70, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Speicherzugriffsfehler
```

I also tried the last weekly (plover-weekly-v3.0.0-93.gb7a630a) directly the sources. In this case I can do one search, which works but not a second one. I can't enter anything after the first search. The window does not crash. If I close it and open it again I can do another search but afterwards I also can't enter new search terms. There is no cursor.

This is the output in the terminal I got when using the weekly build (I searched for "which"):
```
myusername@shuttle:~/Downloads/plover-weekly-v3.0.0-93.gb7a630a$ ./launch.sh 
running launch
running egg_info
writing requirements to plover.egg-info/requires.txt
writing plover.egg-info/PKG-INFO
writing top-level names to plover.egg-info/top_level.txt
writing dependency_links to plover.egg-info/dependency_links.txt
writing entry points to plover.egg-info/entry_points.txt
reading manifest file 'plover.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'plover.egg-info/SOURCES.txt'
Xlib.protocol.request.QueryExtension
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/gui/dictionary_editor.py", line 337, in GetAttr
    if self.store.is_row_read_only(row):
  File "/home/myusername/Downloads/plover-weekly-v3.0.0-93.gb7a630a/plover/dictionary_editor_store.py", line 71, in is_row_read_only
    item = self.sorted_keys[row]
IndexError: list index out of range

(plover:6694): GLib-CRITICAL **: Source ID 805 was not found when attempting to remove it

(plover:6694): GLib-CRITICAL **: Source ID 1027 was not found when attempting to remove it
```

**Comment by morinted** [comment]
@percidae are you using custom dictionaries? Can you try with the default dictionaries and see if the problem occurs? If it doesn't, then it's a matter of finding out which dictionary is causing issue.

**Comment by benoit-pierre** [comment]
It's known problem: the code is threaded, with concurrent accesses to the GUI (GTK), a recipe for crashes.

**Comment by benoit-pierre** [comment]
It also look like it's entirely possible to start multiple filter threads...

```
(<Thread(Thread-5, started 47223613511424)>, 'filter')
(<Thread(Thread-5, started 47223613511424)>, 'filter done')
(<Thread(Thread-6, started 47223613511424)>, 'filter')
(<Thread(Thread-6, started 47223613511424)>, 'filter done')
(<Thread(Thread-7, started 47223613511424)>, 'filter')
(<Thread(Thread-8, started 47223611410176)>, 'filter')
(<Thread(Thread-9, started 47224140928768)>, 'filter')
(<Thread(Thread-7, started 47223613511424)>, 'filter done')
(<Thread(Thread-10, started 47223613511424)>, 'filter')
(<Thread(Thread-11, started 47224143030016)>, 'filter')
(<Thread(Thread-12, started 47224145131264)>, 'filter')
(<Thread(Thread-8, started 47223611410176)>, 'filter done')
(<Thread(Thread-9, started 47224140928768)>, 'filter done')
(<Thread(Thread-10, started 47223613511424)>, 'filter done')
(<Thread(Thread-11, started 47224143030016)>, 'filter done')
(<Thread(Thread-12, started 47224145131264)>, 'filter done')
```

I think this should help with regard to crashes:
```diff
diff --git i/plover/gui/dictionary_editor.py w/plover/gui/dictionary_editor.py
--- i/plover/gui_wx/dictionary_editor.py
+++ w/plover/gui_wx/dictionary_editor.py
@@ -137,12 +137,14 @@ class DictionaryEditor(wx.Dialog):
         self.last_window = util.GetForegroundWindow()

     def _do_filter(self, event=None):
-        threading.Thread(target=self._do_filter_thread).start()
-
-    def _do_filter_thread(self):
-        self.store.ApplyFilter(self.filter_by_stroke.GetValue(),
-                               self.filter_by_translation.GetValue())
-        self.grid.RefreshView()
+        strokes_filter = self.filter_by_stroke.GetValue()
+        translation_filter = self.filter_by_translation.GetValue()
+        threading.Thread(target=self._do_filter_thread,
+                         args=(strokes_filter, translation_filter)).start()
+
+    def _do_filter_thread(self, strokes_filter, translation_filter):
+        self.store.ApplyFilter(strokes_filter, translation_filter)
+        wx.CallAfter(self.grid.RefreshView)

     def _insert_new(self, event=None):
         self.grid.InsertNew()
```

**Comment by benoit-pierre** [comment]
Additionally, just moving the mouse over the table will generate a bunch of calls to the dictionary store, so if you do this while the filter is still running...

**Comment by benoit-pierre** [comment]
IMHO, we should just remove the thread:
```diff
diff --git i/plover/gui/dictionary_editor.py w/plover/gui/dictionary_editor.py
--- i/plover/gui/dictionary_editor.py
+++ w/plover/gui/dictionary_editor.py
@@ -1,4 +1,3 @@
-import threading
 import wx
 from wx.lib.utils import AdjustRectToScreen
 import plover.gui_wx.util as util
@@ -137,9 +136,6 @@ class DictionaryEditor(wx.Dialog):
         self.last_window = util.GetForegroundWindow()

     def _do_filter(self, event=None):
-        threading.Thread(target=self._do_filter_thread).start()
-
-    def _do_filter_thread(self):
         self.store.ApplyFilter(self.filter_by_stroke.GetValue(),
                                self.filter_by_translation.GetValue())
         self.grid.RefreshView()
```

**Comment by percidae** [comment]
I downloaded main.json, commands.json and user.json from the github repository and used these. (Before, I didn't use custom dictionaries, just probably older versions of the files. My user.json had only one entry.)
Both Plover versions still behave the same way, as far as I can see.

**Comment by morinted** [comment]
@benoit-pierre removing the thread sounds like a good idea, would you PR it?
