### ISSUE TITLE
setup.py clean requires pytest unnecessarily

### ISSUE THREAD

**Issue by hlieberman** [openstenoproject/plover#561]
Classification: Bug

Reproducibility: Always

## Summary
setup.py clean requires pytest unnecessarily

## Steps to Reproduce

python setup.py clean

## Expected Results

Clean successfuly

## Actual Results
```
I: pybuild base:184: python2.7-dbg setup.py clean 

Note: Bypassing https://pypi.python.org/simple/pytest/ (disallowed host; see http://bit.ly/1dg9ijs for details).

Couldn't find index page for 'pytest' (maybe misspelled?)

Note: Bypassing https://pypi.python.org/simple/ (disallowed host; see http://bit.ly/1dg9ijs for details).

No local packages or download links found for pytest
Traceback (most recent call last):
  File "setup.py", line 367, in <module>
    **kwargs
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 657, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest')
[107699 refs]
E: pybuild pybuild:274: clean: plugin distutils failed with: exit code=1: python2.7-dbg setup.py clean 
```

## Version

3.0.0

**Comment by morinted** [comment]
@benoit-pierre can you take a look at this issue?

**Comment by benoit-pierre** [comment]
I don't see a way around this:`pytest` is in `setup_requires`, so if you did not install the requirements before, setuptools will automatically try to install it in `.eggs`. Which should not be a problem, unless you're building a Debian package and the PyPi index is disabled, in which case the fix is simple: add `python-pytest` to build `Build-Depends`.

**Comment by morinted** [comment]
I think that's a reasonable compromise.
