### ISSUE TITLE
Plover fails to launch with dictionary-related error

### ISSUE THREAD

**Issue by arxanas** [openstenoproject/plover#748]
Classification: Crash

Reproducibility: Always

## Summary

Plover throws an exception on launch on master.

## Steps to Reproduce

1. Run `./launch.sh`.

## Expected Results

2. The main window renders and Plover is usable.

## Actual Results

2. Plover crashes with the following output:

```
running launch
running build_py
running build_ui
Cannot find file: suggestions.svg
pyrcc5  /Users/waleedk/Workspace/plover/plover/gui_qt/resources/resources.qrc -o /Users/waleedk/Workspace/plover/plover/gui_qt/resources_rc.py
running hook 'fix_icons'
running hook 'gettext'
skipping /Users/waleedk/Workspace/plover/plover/gui_qt/about_dialog.ui, up to date
pyuic5 --from-import /Users/waleedk/Workspace/plover/plover/gui_qt/add_translation.ui -o /Users/waleedk/Workspace/plover/plover/gui_qt/add_translation_ui.py
running hook 'fix_icons'
running hook 'gettext'
skipping /Users/waleedk/Workspace/plover/plover/gui_qt/config_file_widget.ui, up to date
skipping /Users/waleedk/Workspace/plover/plover/gui_qt/config_keyboard_widget.ui, up to date
skipping /Users/waleedk/Workspace/plover/plover/gui_qt/config_serial_widget.ui, up to date
skipping /Users/waleedk/Workspace/plover/plover/gui_qt/config_window.ui, up to date
pyuic5 --from-import /Users/waleedk/Workspace/plover/plover/gui_qt/dictionaries_widget.ui -o /Users/waleedk/Workspace/plover/plover/gui_qt/dictionaries_widget_ui.py
running hook 'fix_icons'
running hook 'gettext'
skipping /Users/waleedk/Workspace/plover/plover/gui_qt/dictionary_editor.ui, up to date
skipping /Users/waleedk/Workspace/plover/plover/gui_qt/lookup_dialog.ui, up to date
skipping /Users/waleedk/Workspace/plover/plover/gui_qt/main_window.ui, up to date
skipping /Users/waleedk/Workspace/plover/plover/gui_qt/paper_tape.ui, up to date
skipping /Users/waleedk/Workspace/plover/plover/gui_qt/suggestions_dialog.ui, up to date
skipping /Users/waleedk/Workspace/plover/plover/gui_qt/suggestions_widget.ui, up to date
running compile_catalog
compiling catalog plover/gui_qt/messages/fr/LC_MESSAGES/plover.po to plover/gui_qt/messages/fr/LC_MESSAGES/plover.mo
copying plover/config.py -> build/lib/plover
copying plover/engine.py -> build/lib/plover
copying plover/exception.py -> build/lib/plover
copying plover/steno_dictionary.py -> build/lib/plover
copying plover/suggestions.py -> build/lib/plover
copying plover/dictionary/base.py -> build/lib/plover/dictionary
copying plover/dictionary/json_dict.py -> build/lib/plover/dictionary
copying plover/dictionary/loading_manager.py -> build/lib/plover/dictionary
copying plover/dictionary/rtfcre_dict.py -> build/lib/plover/dictionary
copying plover/gui_qt/add_translation.py -> build/lib/plover/gui_qt
copying plover/gui_qt/add_translation_ui.py -> build/lib/plover/gui_qt
copying plover/gui_qt/config_window.py -> build/lib/plover/gui_qt
copying plover/gui_qt/dictionaries_widget.py -> build/lib/plover/gui_qt
copying plover/gui_qt/dictionaries_widget_ui.py -> build/lib/plover/gui_qt
copying plover/gui_qt/dictionary_editor.py -> build/lib/plover/gui_qt
copying plover/gui_qt/engine.py -> build/lib/plover/gui_qt
copying plover/gui_qt/resources_rc.py -> build/lib/plover/gui_qt
copying plover/oslayer/xkeyboardcontrol.py -> build/lib/plover/oslayer
copying plover/system/__init__.py -> build/lib/plover/system
copying plover/system/english_stenotype.py -> build/lib/plover/system
running egg_info
writing plover.egg-info/PKG-INFO
writing dependency_links to plover.egg-info/dependency_links.txt
writing entry points to plover.egg-info/entry_points.txt
writing top-level names to plover.egg-info/top_level.txt
writing requirements to plover.egg-info/requires.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'plover.egg-info/SOURCES.txt'
copying plover/gui_qt/add_translation.ui -> build/lib/plover/gui_qt
copying plover/gui_qt/dictionaries_widget.ui -> build/lib/plover/gui_qt
copying plover/gui_qt/messages/fr/LC_MESSAGES/plover.mo -> build/lib/plover/gui_qt/messages/fr/LC_MESSAGES
copying plover/gui_qt/resources/dictionary_error.svg -> build/lib/plover/gui_qt/resources
copying plover/gui_qt/resources/dictionary_favorite.svg -> build/lib/plover/gui_qt/resources
copying plover/gui_qt/resources/dictionary_loading.svg -> build/lib/plover/gui_qt/resources
copying plover/gui_qt/resources/dictionary_normal.svg -> build/lib/plover/gui_qt/resources
copying plover/gui_qt/resources/dictionary_readonly.svg -> build/lib/plover/gui_qt/resources
copying plover/gui_qt/resources/resources.qrc -> build/lib/plover/gui_qt/resources
running build_ext
2017-04-19 14:55:53,192 [MainThread] ERROR: invalid system dictionaries, resetting to default
Traceback (most recent call last):
  File "/Users/waleedk/Workspace/plover/plover/config.py", line 237, in get_dictionaries
    for d in json.loads(dictionaries)]
  File "/Users/waleedk/Workspace/plover/plover/config.py", line 237, in <listcomp>
    for d in json.loads(dictionaries)]
  File "/Users/waleedk/Workspace/plover/plover/config.py", line 129, in from_dict
    return DictionaryConfig(**d)
TypeError: type object argument after ** must be a mapping, not str
```

## Version

Plover version 8a51e88726c19e01fc16c5f1980c2b52c850a25f.

`git bisect` indicates that the problem is introduced in 20ac3a758b14afdbdecbf80474d2ac508d8a50b5.

Installed via: source

## Notes

I tried uninstalling `plover-python-dictionary` and removing Python dictionaries from my `plover.cfg`, but the problem persists. Here is my `plover.cfg`:

```
[Config Frame]
width = 486
height = 304
x = 1831
y = 447

[Main Frame]
x = 4
y = 23

[Machine Configuration]
machine_type = Keyboard
auto_start = False

[Logging Configuration]
log_file = strokes.log
enable_stroke_logging = True
enable_translation_logging = True

[Stroke Display]
show = False
style = Paper
x = 2311
y = 613

[Suggestions Display]
show = True
x = 2316
y = 819
on_top = False

[Translation Frame]
opacity = 100
x = 264
y = 180

[Output Configuration]
space_placement = Before Output
start_attached = True
start_capitalized = True
undo_levels = 100

[Lookup Frame]
x = 1164
y = 196

[Dictionary Editor Frame]
x = 640
y = 77

[System: English Stenotype]
keymap[keyboard] = [["#", ["8", "=", "5", "3", "7", "6", "4", "9", "2", "0", "1", "-"]], ["*", ["t", "g", "h", "y"]], ["-B", ["k"]], ["-D", ["["]], ["-E", ["n"]], ["-F", ["u"]], ["-G", ["l"]], ["-L", ["o"]], ["-P", ["i"]], ["-R", ["j"]], ["-S", [";"]], ["-T", ["p"]], ["-U", ["m"]], ["-Z", ["'"]], ["A-", ["c"]], ["H-", ["r"]], ["K-", ["s"]], ["O-", ["v"]], ["P-", ["e"]], ["R-", ["f"]], ["S-", ["q", "a"]], ["T-", ["w"]], ["W-", ["d"]], ["arpeggiate", ["space"]], ["no-op", ["]", "/", "b", ".", "z", ",", "x", "\\"]]]
# dictionaries = ["main.json", "commands.json", "cross_platform_movement_v1.json", "lh_modifier_keys_v1.json", "pokemon_v1.json", "user-osx.json", "programming.json", "chess.json", "captioning.json", "multiword-briefs.json", "user.json", "multiword_briefs.py", "user-incubation.json"]
dictionaries = ["main.json", "commands.json", "cross_platform_movement_v1.json", "lh_modifier_keys_v1.json", "pokemon_v1.json", "user-osx.json", "programming.json", "chess.json", "captioning.json", "multiword-briefs.json", "user.json", "user-incubation.json"]

[Stentura]
parity = N
baudrate = 9600
bytesize = 8
xonxoff = False
rtscts = False
timeout = 2.0
stopbits = 1
port = None

[Passport]
parity = N
baudrate = 38400
bytesize = 8
xonxoff = False
rtscts = False
timeout = 2.0
stopbits = 1
port = None

[Gemini PR]
parity = N
baudrate = 9600
bytesize = 8
xonxoff = False
rtscts = False
timeout = 2.0
stopbits = 1
port = None

[Keyboard]
arpeggiate = False

[Serial Config Frame]
x = 704
y = 197

[TX Bolt]
parity = N
baudrate = 9600
bytesize = 8
xonxoff = False
rtscts = False
timeout = 0.5
stopbits = 1
port = /dev/cu.usbserial-ADAPHOLfN

[Startup]
start minimized = False

[Dictionary Configuration]
dictionary_file1 = main.json
dictionary_file2 = commands.json
dictionary_file3 = cross_platform_movement_v1.json
dictionary_file4 = lh_modifier_keys_v1.json
dictionary_file5 = user-osx.json
dictionary_file6 = programming.json
dictionary_file7 = chess.json
dictionary_file8 = captioning.json
dictionary_file9 = multiword-briefs.json
dictionary_file10 = user.json
dictionary_file11 = user-incubation.json
```

## Configuration

OS: macOS

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.3
BuildVersion:   16D32
```

**Comment by benoit-pierre** [comment]
Not a bug. The format of the configuration for dictionaries changed. The code will still support loading a configuration file from the latest stable, but not from master before this change. Remove the `dictionaries = ["...` line and the old `[Dictionary Configuration]` block and re-add your dictionaries.

**Comment by arxanas** [comment]
Looks like that works. You're probably already aware, but it looks like trying to add a Python dictionary using `plover-python-dictionary` fails with this error:

```
2017-04-19 15:48:07,308 [Dummy-1] ERROR: loading dictionary `multiword_briefs.py` failed: module 'plover_python_dictionary' has no attribute 'load'
```

**Comment by benoit-pierre** [comment]
Yes, I know, I've updated my code locally but not yet pushed it.
