### ISSUE TITLE
Missing `_ui` modules in `plover.gui_qt` package

### ISSUE THREAD

**Issue by mkrnr** [openstenoproject/plover#785]
Classification: Bug

Reproducibility: Always

## Summary

When executing, a number of modules in the `plover.gui_qt` package that end with `_ui` seem to be missing which crashes the program. 

## Steps to Reproduce

1. Install latest version via the AUR repository `plover-git`.
2. Start the program in the command line.

## Expected Results

3. The program should start.

## Actual Results

3. The following Traceback is shown:
```
martin@arch[I]:~% plover
2017-06-25 23:46:57,373 [MainThread] ERROR: error loading gui.qt.tool plugin: add_translation (from plover.gui_qt.add_translation)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/plover/registry.py", line 52, in register_plugin_from_entrypoint
    obj = entrypoint.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/plover/gui_qt/add_translation.py", line 11, in <module>
    from plover.gui_qt.add_translation_ui import Ui_AddTranslation
ModuleNotFoundError: No module named 'plover.gui_qt.add_translation_ui'
2017-06-25 23:46:57,377 [MainThread] ERROR: error loading gui.qt.tool plugin: lookup (from plover.gui_qt.lookup_dialog)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/plover/registry.py", line 52, in register_plugin_from_entrypoint
    obj = entrypoint.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/plover/gui_qt/lookup_dialog.py", line 6, in <module>
    from plover.gui_qt.lookup_dialog_ui import Ui_LookupDialog
ModuleNotFoundError: No module named 'plover.gui_qt.lookup_dialog_ui'
2017-06-25 23:46:57,380 [MainThread] ERROR: error loading gui.qt.tool plugin: paper_tape (from plover.gui_qt.paper_tape)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/plover/registry.py", line 52, in register_plugin_from_entrypoint
    obj = entrypoint.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/plover/gui_qt/paper_tape.py", line 14, in <module>
    from plover.gui_qt.paper_tape_ui import Ui_PaperTape
ModuleNotFoundError: No module named 'plover.gui_qt.paper_tape_ui'
2017-06-25 23:46:57,383 [MainThread] ERROR: error loading gui.qt.tool plugin: suggestions (from plover.gui_qt.suggestions_dialog)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/plover/registry.py", line 52, in register_plugin_from_entrypoint
    obj = entrypoint.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/plover/gui_qt/suggestions_dialog.py", line 17, in <module>
    from plover.gui_qt.suggestions_dialog_ui import Ui_SuggestionsDialog
ModuleNotFoundError: No module named 'plover.gui_qt.suggestions_dialog_ui'
Unexpected error: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/plover/main.py", line 117, in main
    code = gui.main(config)
  File "/usr/lib/python3.6/site-packages/plover/gui_qt/main.py", line 90, in main
    app = Application(config, use_qt_notifications)
  File "/usr/lib/python3.6/site-packages/plover/gui_qt/main.py", line 28, in __init__
    from plover.gui_qt.main_window import MainWindow
  File "/usr/lib/python3.6/site-packages/plover/gui_qt/main_window.py", line 18, in <module>
    from plover.gui_qt.main_window_ui import Ui_MainWindow
ModuleNotFoundError: No module named 'plover.gui_qt.main_window_ui'

QApplication: invalid style override passed, ignoring it.
Exception ignored in: <bound method Application.__del__ of <plover.gui_qt.main.Application object at 0x7fd21364c6d8>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/plover/gui_qt/main.py", line 66, in __del__
    del self._win
AttributeError: _win
[2] martin@arch[I]:~% 
```

## Version

Plover version 4.0.0.dev0.144.gded92d7

Installed via: AUR repository `plover-git`

## Notes

For me the Traceback makes sense since there really are no such modules but probably I'm missing something here...

## Configuration

Arch Linux, i3 Window Manager, Python 3.6.1

**Comment by benoit-pierre** [comment]
We're getting it by this setuptools bug: https://github.com/pypa/setuptools/issues/1054

As a workaround, `pip install --user pyqt-distutils` before installing from AUR.

**Comment by mkrnr** [comment]
Thank you @benoit-pierre! This solved the problem.

**Comment by benoit-pierre** [comment]
With #791 merged, using Plover's setup.py will now reliably fail if some setup requirements are missing instead of building an incomplete version.
