### ISSUE TITLE
Error when running plover from appimage: UnicodeDecodeError

### ISSUE THREAD

**Issue by lukeoftheaura** [openstenoproject/plover#919]
## Summary

When I run plover from either the latest appimage or the AUR `plover-git` package, I get this error:
```
2018-03-15 21:58:22,375 [Dummy-1] ERROR: engine start failed
Traceback (most recent call last):
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/plover/engine.py", line 136, in run
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/plover/engine.py", line 149, in _start
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/plover/engine.py", line 239, in _update
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/plover/machine/keyboard.py", line 66, in start_capture
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/plover/oslayer/xkeyboardcontrol.py", line 166, in __init__
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/plover/oslayer/xkeyboardcontrol.py", line 171, in _update_devices
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/Xlib/ext/xinput.py", line 426, in query_device
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1381, in reply
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/Xlib/protocol/display.py", line 613, in send_and_recv
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/Xlib/protocol/display.py", line 705, in parse_response
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/Xlib/protocol/display.py", line 793, in parse_request_response
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1393, in _parse_response
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1205, in parse_binary
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 533, in parse_binary_value
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1205, in parse_binary
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 445, in parse_binary_value
  File "/home/travis/build/openstenoproject/plover/build/appimage/plover.AppDir/usr/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 38, in decode_string
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 19: ordinal not in range(128)
```

## Reproducing

Run plover from the latest appimage or the aur git package on my system.

## Plover Version

Plover 4.0.0.dev6+5.ga564116

## System

Linux, Antergos 64-bit. Same problem with both `plover-git` AUR package and appimage.

**Comment by benoit-pierre** [comment]
It's an issue in `python-xlib`. Is the error new? Any new device connected to your PC? What's the output of `xinput list --long `?

**Comment by lukeoftheaura** [comment]
I only seem to get the error when my sidewinder X4 is connected, when I only have my normal (Cherry G80-3000) keyboard connected plover works fine.

**Comment by benoit-pierre** [comment]
That's weird, and what is the output of the xinput command above?

**Comment by lukeoftheaura** [comment]
When I don't have the sidewinder connected:
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
	Reporting 7 classes:
		Class originated from: 10. Type: XIButtonClass
		Buttons supported: 10
		Button labels: "Button Left" "Button Middle" "Button Right" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right" "Button Side" "Button Extra" None
		Button state:
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Rel X
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Rel Y
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 2:
		  Label: Rel Horiz Scroll
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 3:
		  Label: Rel Vert Scroll
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIScrollClass
		Scroll info for Valuator 2
		  type: 2 (horizontal)
		  increment: 15.000000
		  flags: 0x0
		Class originated from: 10. Type: XIScrollClass
		Scroll info for Valuator 3
		  type: 1 (vertical)
		  increment: 15.000000
		  flags: 0x0

⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
	Reporting 3 classes:
		Class originated from: 4. Type: XIButtonClass
		Buttons supported: 10
		Button labels: "Button Left" "Button Middle" "Button Right" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right" None None None
		Button state:
		Class originated from: 4. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Rel X
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 4. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Rel Y
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative

⎜   ↳ Logitech USB Trackball                  	id=10	[slave  pointer  (2)]
	Reporting 7 classes:
		Class originated from: 10. Type: XIButtonClass
		Buttons supported: 9
		Button labels: "Button Left" "Button Middle" "Button Right" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right" "Button Side" "Button Extra"
		Button state:
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Rel X
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Rel Y
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 2:
		  Label: Rel Horiz Scroll
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 3:
		  Label: Rel Vert Scroll
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIScrollClass
		Scroll info for Valuator 2
		  type: 2 (horizontal)
		  increment: 15.000000
		  flags: 0x0
		Class originated from: 10. Type: XIScrollClass
		Scroll info for Valuator 3
		  type: 1 (vertical)
		  increment: 15.000000
		  flags: 0x0

⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
	Reporting 1 classes:
		Class originated from: 9. Type: XIKeyClass
		Keycodes supported: 248

    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 5. Type: XIKeyClass
		Keycodes supported: 248

    ↳ Power Button                            	id=6	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 6. Type: XIKeyClass
		Keycodes supported: 248

    ↳ Power Button                            	id=7	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 7. Type: XIKeyClass
		Keycodes supported: 248

    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 8. Type: XIKeyClass
		Keycodes supported: 248

    ↳ HID 046a:0011                           	id=9	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 9. Type: XIKeyClass
		Keycodes supported: 248

    ↳ Eee PC WMI hotkeys                      	id=11	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 11. Type: XIKeyClass
		Keycodes supported: 248

```
When I do:
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
	Reporting 7 classes:
		Class originated from: 10. Type: XIButtonClass
		Buttons supported: 10
		Button labels: "Button Left" "Button Middle" "Button Right" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right" "Button Side" "Button Extra" None
		Button state:
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Rel X
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Rel Y
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 2:
		  Label: Rel Horiz Scroll
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 3:
		  Label: Rel Vert Scroll
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIScrollClass
		Scroll info for Valuator 2
		  type: 2 (horizontal)
		  increment: 15.000000
		  flags: 0x0
		Class originated from: 10. Type: XIScrollClass
		Scroll info for Valuator 3
		  type: 1 (vertical)
		  increment: 15.000000
		  flags: 0x0

⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
	Reporting 3 classes:
		Class originated from: 4. Type: XIButtonClass
		Buttons supported: 10
		Button labels: "Button Left" "Button Middle" "Button Right" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right" None None None
		Button state:
		Class originated from: 4. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Rel X
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 4. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Rel Y
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative

⎜   ↳ Logitech USB Trackball                  	id=10	[slave  pointer  (2)]
	Reporting 7 classes:
		Class originated from: 10. Type: XIButtonClass
		Buttons supported: 9
		Button labels: "Button Left" "Button Middle" "Button Right" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right" "Button Side" "Button Extra"
		Button state:
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Rel X
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Rel Y
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 2:
		  Label: Rel Horiz Scroll
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 3:
		  Label: Rel Vert Scroll
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 10. Type: XIScrollClass
		Scroll info for Valuator 2
		  type: 2 (horizontal)
		  increment: 15.000000
		  flags: 0x0
		Class originated from: 10. Type: XIScrollClass
		Scroll info for Valuator 3
		  type: 1 (vertical)
		  increment: 15.000000
		  flags: 0x0

⎜   ↳ Microsoft Microsoft® SiderWinderTM X4 Keyboard	id=13	[slave  pointer  (2)]
	Reporting 7 classes:
		Class originated from: 13. Type: XIButtonClass
		Buttons supported: 7
		Button labels: "Button Left" "Button Middle" "Button Right" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right"
		Button state:
		Class originated from: 13. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Rel X
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 13. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Rel Y
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 13. Type: XIValuatorClass
		Detail for Valuator 2:
		  Label: Rel Horiz Scroll
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 13. Type: XIValuatorClass
		Detail for Valuator 3:
		  Label: Rel Vert Scroll
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 13. Type: XIScrollClass
		Scroll info for Valuator 2
		  type: 2 (horizontal)
		  increment: 15.000000
		  flags: 0x0
		Class originated from: 13. Type: XIScrollClass
		Scroll info for Valuator 3
		  type: 1 (vertical)
		  increment: 15.000000
		  flags: 0x0

⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
	Reporting 1 classes:
		Class originated from: 9. Type: XIKeyClass
		Keycodes supported: 248

    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 5. Type: XIKeyClass
		Keycodes supported: 248

    ↳ Power Button                            	id=6	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 6. Type: XIKeyClass
		Keycodes supported: 248

    ↳ Power Button                            	id=7	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 7. Type: XIKeyClass
		Keycodes supported: 248

    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 8. Type: XIKeyClass
		Keycodes supported: 248

    ↳ HID 046a:0011                           	id=9	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 9. Type: XIKeyClass
		Keycodes supported: 248

    ↳ Eee PC WMI hotkeys                      	id=11	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 11. Type: XIKeyClass
		Keycodes supported: 248

    ↳ Microsoft Microsoft® SiderWinderTM X4 Keyboard	id=12	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 12. Type: XIKeyClass
		Keycodes supported: 248

    ↳ Microsoft Microsoft® SiderWinderTM X4 Keyboard	id=14	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 14. Type: XIKeyClass
		Keycodes supported: 248
```

**Comment by benoit-pierre** [comment]
Prety sure this is what is causing the issue: `Microsoft Microsoft®`<- `SiderWinderTM X4 Keyboard`

**Comment by Erudition** [comment]
Same for me. No SideWinder, just a normal Microsoft Keyboard. Fresh AppImage install.

**Comment by benoit-pierre** [comment]
@Erudition: can you confirm the output from `xinput list` is similar (you've got a `®` somewhere)?

**Comment by Erudition** [comment]
@benoit-pierre Indeed.
`⎜   ↳ Microsoft Natural® Ergonomic Keyboard 4000        id=10   [slave  pointer  (2)]`
