### ISSUE TITLE
Plover crashes exiting lookup when accessed via a shortcut

### ISSUE THREAD

**Issue by Twey** [openstenoproject/plover#926]
## Summary

Plover will crash with a type error if the lookup window is closed after being opened with a Plover command (default: `KHR-P`).

### Do:
- Run Plover 4.0.0.dev6
- Type `KHR-P` to launch the lookup window.
- Close the window through any means (escape, window manager).

### Observe:
Plover crashes with the error:
```
Traceback (most recent call last):
  File "/nix/store/p7yzbwak770ivqlizq2hyw2dz25ay30i-python3.6-plover-4.0.0.dev6/lib/python3.6/site-packages/plover/gui_qt/main_window.py", line 173, in on_finished
    wmctrl.SetForegroundWindow(previous_window)
  File "/nix/store/p7yzbwak770ivqlizq2hyw2dz25ay30i-python3.6-plover-4.0.0.dev6/lib/python3.6/site-packages/plover/oslayer/xwmctrl.py", line 47, in set_foreground_window
    desktop = self._get_wm_property(window, atom)
  File "/nix/store/p7yzbwak770ivqlizq2hyw2dz25ay30i-python3.6-plover-4.0.0.dev6/lib/python3.6/site-packages/plover/oslayer/xwmctrl.py", line 23, in _get_wm_property
    X.AnyPropertyType)
  File "/nix/store/0sw234d4fpifp5bdphilz6irw212rwyk-python3.6-xlib-0.17/lib/python3.6/site-packages/Xlib/xobject/drawable.py", line 472, in get_full_property
    prop = self.get_property(property, property_type, 0, sizehint)
  File "/nix/store/0sw234d4fpifp5bdphilz6irw212rwyk-python3.6-xlib-0.17/lib/python3.6/site-packages/Xlib/xobject/drawable.py", line 461, in get_property
    long_length = length)
  File "/nix/store/0sw234d4fpifp5bdphilz6irw212rwyk-python3.6-xlib-0.17/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1351, in __init__
    self._binary = self._request.to_binary(*args, **keys)
  File "/nix/store/0sw234d4fpifp5bdphilz6irw212rwyk-python3.6-xlib-0.17/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1060, in to_binary
    static_part = struct.pack(self.static_codes, *pack_items)
struct.error: required argument is not an integer
Aborted
```

## Plover Version

4.0.0.dev6

## System

NixOS nixos-18.03pre130932.cc4677c36ee
To reproduce environment:
```nix-env -f https://github.com/Twey/nixpkgs/archive/plover-4.0.0.dev6.tar.gz -i plover.dev```
(may take a while — the Qt versions used are not yet precompiled)

**Comment by benoit-pierre** [comment]
What's the currently focused window when you use the shortcut? Can you test with master with the following debug trace:
```diff
 plover/gui_qt/main_window.py | 1 +
 1 file changed, 1 insertion(+)

diff --git i/plover/gui_qt/main_window.py w/plover/gui_qt/main_window.py
index 8210d5d1..bebc8401 100644
--- i/plover/gui_qt/main_window.py
+++ w/plover/gui_qt/main_window.py
@@ -170,6 +170,7 @@ class MainWindow(QMainWindow, Ui_MainWindow, WindowState):
                 del self._active_dialogs[name]
                 dialog.deleteLater()
                 if manage_windows:
+                    print('previous_window', previous_window)
                     wmctrl.SetForegroundWindow(previous_window)
             dialog.finished.connect(on_finished)
         dialog.show()
```

**Comment by Twey** [comment]
It doesn't seem to depend on the currently-focused window — I can crash it just as well launching from the Plover main window or from my terminal, but it must be via the `KHR-P` chord: clicking the ‘lookup’ button in the UI doesn't cause this behaviour.

The patch prints `None`:
```
[twey@uruz:~/nix/nixpkgs]$ ./result/bin/plover
```
(`KHR-P`, close via window manager)
```
previous_window None
Traceback (most recent call last):
  File "/nix/store/qjm21k1hn2wwphpaiwwlsw22jghbqmwx-python3.6-plover-4.0.0.dev6/lib/python3.6/site-packages/plover/gui_qt/main_window.py", line 174, in on_finished
    wmctrl.SetForegroundWindow(previous_window)
  File "/nix/store/qjm21k1hn2wwphpaiwwlsw22jghbqmwx-python3.6-plover-4.0.0.dev6/lib/python3.6/site-packages/plover/oslayer/xwmctrl.py", line 47, in set_foreground_window
    desktop = self._get_wm_property(window, atom)
  File "/nix/store/qjm21k1hn2wwphpaiwwlsw22jghbqmwx-python3.6-plover-4.0.0.dev6/lib/python3.6/site-packages/plover/oslayer/xwmctrl.py", line 23, in _get_wm_property
    X.AnyPropertyType)
  File "/nix/store/0sw234d4fpifp5bdphilz6irw212rwyk-python3.6-xlib-0.17/lib/python3.6/site-packages/Xlib/xobject/drawable.py", line 472, in get_full_property
    prop = self.get_property(property, property_type, 0, sizehint)
  File "/nix/store/0sw234d4fpifp5bdphilz6irw212rwyk-python3.6-xlib-0.17/lib/python3.6/site-packages/Xlib/xobject/drawable.py", line 461, in get_property
    long_length = length)
  File "/nix/store/0sw234d4fpifp5bdphilz6irw212rwyk-python3.6-xlib-0.17/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1351, in __init__
    self._binary = self._request.to_binary(*args, **keys)
  File "/nix/store/0sw234d4fpifp5bdphilz6irw212rwyk-python3.6-xlib-0.17/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1060, in to_binary
    static_part = struct.pack(self.static_codes, *pack_items)
struct.error: required argument is not an integer
Aborted
```

**Comment by Twey** [comment]
It seems `_NET_ACTIVE_WINDOW` is an EWMH extension, which I don't have my window manager (xmonad) configured to handle.  Setting that up fixes the crash, but perhaps Plover should handle this case gracefully anyway?

**Comment by benoit-pierre** [comment]
Yeah, not try to restore the previous window if it could not get its id.

**Comment by benoit-pierre** [comment]
Can you confirm #929 fix your issue?

**Comment by Twey** [comment]
Confirm. I was going to submit a patch but wasn't sure if you should maybe disable `manage_windows` entirely in this case.
