### ISSUE TITLE
Cannot launch/install plover on Ubuntu 18.04. ModuleNotFoundError: No module named 'PyQt5.sip'

### ISSUE THREAD

**Issue by Elktro** [openstenoproject/plover#985]
## Summary

Cannot launch or install plover after I upgraded to Ubuntu 18.04 from 16.04. Gives error: "ModuleNotFoundError: No module named 'PyQt5.sip'"

## Reproducing

```
myusername@mycomputer:~/sources/temp_plover$ git clone https://github.com/openstenoproject/plover.git
Cloning into 'plover'...
remote: Counting objects: 8848, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 8848 (delta 4), reused 14 (delta 4), pack-reused 8830
Receiving objects: 100% (8848/8848), 20.71 MiB | 3.50 MiB/s, done.
Resolving deltas: 100% (6087/6087), done.
myusername@mycomputer:~/sources/temp_plover$ cd plover/
myusername@mycomputer:~/sources/temp_plover/plover$ ./launch.sh 
running launch
running build_py
running build_ui
running egg_info
creating plover.egg-info
writing plover.egg-info/PKG-INFO
writing dependency_links to plover.egg-info/dependency_links.txt
writing entry points to plover.egg-info/entry_points.txt
writing requirements to plover.egg-info/requires.txt
writing top-level names to plover.egg-info/top_level.txt
writing manifest file 'plover.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'tox.ini'
warning: no previously-included files found matching 'plover/gui_qt/*_rc.py'
warning: no previously-included files found matching 'plover/gui_qt/*_ui.py'
writing manifest file 'plover.egg-info/SOURCES.txt'
generating plover/gui_qt/about_dialog_ui.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/myusername/sources/temp_plover/plover/.eggs/PyQt5-5.11.2-py3.6-linux-x86_64.egg/PyQt5/uic/pyuic.py", line 26, in <module>
    from PyQt5 import QtCore
ModuleNotFoundError: No module named 'PyQt5.sip'
Traceback (most recent call last):
  File "setup.py", line 393, in <module>
    cmdclass=cmdclass,
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 232, in run
    with self.project_on_sys_path():
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/myusername/sources/temp_plover/plover/plover_build_utils/setup.py", line 23, in project_on_sys_path
    self.build_in_place()
  File "/home/myusername/sources/temp_plover/plover/plover_build_utils/setup.py", line 17, in build_in_place
    self.run_command('build_py')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/myusername/sources/temp_plover/plover/plover_build_utils/setup.py", line 157, in run
    self.run_command(command)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/myusername/sources/temp_plover/plover/plover_build_utils/setup.py", line 145, in run
    self._build_ui(src)
  File "/home/myusername/sources/temp_plover/plover/plover_build_utils/setup.py", line 116, in _build_ui
    contents = subprocess.check_output(cmd).decode('utf-8')
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('/usr/bin/python3', '-m', 'PyQt5.uic.pyuic', '--from-import', 'plover/gui_qt/about_dialog.ui')' returned non-zero exit status 1.
```

## Plover Version
Tested with: 685bd3373dcf19817f59070274a33457ff145701

## System
lsb_release -a:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
wmctrl -m
```
Name: GNOME Shell
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A
```

**Comment by nsmarkop** [comment]
It looks like you're cloning the repo and then trying to run from source without installing the dependencies first. Can you install the dependencies to run from source per the documentation [here](https://github.com/openstenoproject/plover/blob/master/linux/README.md) and try launching it again? 

Alternatively, you can download the AppImage release from the [releases page](https://github.com/openstenoproject/plover/releases) if you don't want to set up a development environment in this way.

**Comment by Elktro** [comment]
Now it works. My pip3 was broken.
